<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>$(DefaultTargetFramework)</TargetFramework>
    <LangVersion>preview</LangVersion>
    <RootNamespace>DotnetInspector.Artifacts.Tests</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <IsAotCompatible>false</IsAotCompatible>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\DotnetInspector.Artifacts\DotnetInspector.Artifacts.csproj" />
    <ProjectReference Include="..\..\src\DotnetInspector.Artifacts.Local\DotnetInspector.Artifacts.Local.csproj" />
    <ProjectReference Include="..\..\src\DotnetInspector.Artifacts.Workspaces\DotnetInspector.Artifacts.Workspaces.csproj" />
  </ItemGroup>

</Project>
