<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>$(DefaultTargetFramework)</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../DotnetInspector.MatchBinding.Implementation/DotnetInspector.MatchBinding.Implementation.csproj" />
  </ItemGroup>

</Project>
