<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>$(DefaultTargetFramework)</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>preview</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/DotnetInspector.Artifacts.Local/DotnetInspector.Artifacts.Local.csproj" />
    <ProjectReference Include="../../src/DotnetInspector.Artifacts.Workspaces/DotnetInspector.Artifacts.Workspaces.csproj" />
    <ProjectReference Include="../../src/ILInspector.Metadata/ILInspector.Metadata.csproj" />
  </ItemGroup>
</Project>
