using ILInspector.Decompiler.Tests.Gating;

namespace ILInspector.Decompiler.Tests;

/// <summary>
/// Custom entry point for the decompiler test executable.
/// </summary>
/// <remarks>
/// <para>
/// The auto-generated xUnit v3 entry point is disabled
/// (<c>&lt;XunitAutoGeneratedEntryPoint&gt;false&lt;/XunitAutoGeneratedEntryPoint&gt;</c>
/// in the project file) so we can pre-process a discoverable
/// <c>--gate &lt;preset&gt;</c> flag before delegating to the runner. Presets
/// wrap the <c>Speed</c>/<c>Area</c> trait taxonomy documented in
/// <c>docs/decompiler-correctness-pipeline.md</c> so callers and CI can bound
/// which gates run (notably skipping the multi-hour <c>Corpus</c> sweep)
/// without memorizing MTP filter options.
/// </para>
/// <para>
/// Everything after the <c>--gate</c> handling preserves the xUnit v3
/// auto-generated entry point's automated-mode dispatch and otherwise uses
/// Microsoft Testing Platform.
/// </para>
/// </remarks>
internal static class Program
{
    // Presets over the Speed/Area traits. Order matches --gate list output.
    // internal so GateExpectedClassesTests can assert the pre-merge preset and
    // eng/decompiler-gate-expected-classes.txt name the same classes.
    internal static readonly IReadOnlyList<GatePreset> Presets =
    [
        new("all", "Every test, including all slow gates (default with no --gate)."),
        new("fast", "Skip every slow gate (fast unit lane; matches the PR CI test job).", "--filter-not-trait", "Speed=Slow"),
        new("slow", "Only the slow gates.", "--filter-trait", "Speed=Slow"),
        new("no-corpus", "Everything except the multi-hour Corpus sweep.", "--filter-not-trait", "Area=Corpus"),
        new(
            "pre-merge",
            "The bounded compile-back receipt (matches the PR CI decompiler-gates job).",
            "--filter-class", "ILInspector.Decompiler.Tests.ByteNeutralityGateTests",
            "--filter-class", "ILInspector.Decompiler.Tests.ByteDivergentGateTests",
            "--filter-class", "ILInspector.Decompiler.Tests.SkeletonEmitTests",
            "--filter-class", "ILInspector.Decompiler.Tests.DiffFixtureFidelityTests",
            "--filter-class", "ILInspector.Decompiler.Tests.NestedTargetLookupTests",
            "--filter-class", "ILInspector.DecompilerHarness.AuthoredRebuildFidelityTests",
            "--filter-class", "ILInspector.Decompiler.Tests.AnnotatedCompileBackFailureTests",
            // The gate's own plumbing guard rides along in the preset it guards.
            // Inside the preset it is covered by the same discovery/coverage
            // checks as the correctness gates, so it cannot silently stop running.
            "--filter-class", "ILInspector.Decompiler.Tests.GateExpectedClassesTests",
            "--filter-class", "ILInspector.Decompiler.Tests.MtpGateReceiptTests"),
        new("corpus", "Only the Corpus area (the multi-hour sweep).", "--filter-trait", "Area=Corpus"),
        new("roundtrip", "Only the RoundTrip area (compile-back / ReturnToSender).", "--filter-trait", "Area=RoundTrip"),
        new("fidelity", "Only the Fidelity area.", "--filter-trait", "Area=Fidelity"),
        new("validity", "Only the Validity area.", "--filter-trait", "Area=Validity"),
    ];

    public static int Main(string[] args)
    {
        DiscoveryReceiptExpansion discoveryReceipt =
            MtpDiscoveryReceiptClient.RemoveReceiptArgument(args);
        if (discoveryReceipt.Error is not null)
        {
            Console.Error.WriteLine(discoveryReceipt.Error);
            return 2;
        }

        GateExpansion expansion = GateArgumentExpander.Expand(
            discoveryReceipt.Args,
            Presets);
        switch (expansion.Outcome)
        {
            case GateOutcome.Help:
                Console.Out.WriteLine(expansion.Message);
                return 0;
            case GateOutcome.Error:
                Console.Error.WriteLine(expansion.Message);
                return 2;
        }
        string[] runArgs = expansion.Args as string[] ?? expansion.Args.ToArray();
        if (discoveryReceipt.Path is not null)
        {
            try
            {
                return MtpDiscoveryReceiptClient
                    .CaptureAsync(discoveryReceipt.Path, runArgs)
                    .GetAwaiter().GetResult();
            }
            catch (Exception ex)
            {
                Console.Error.WriteLine(
                    $"error: MTP discovery receipt failed: {ex.Message}");
                return 2;
            }
        }

        string? receiptPath = Environment.GetEnvironmentVariable(
            MtpGateReceiptConsumer.ReceiptPathEnvironmentVariable);
        if (!string.IsNullOrWhiteSpace(receiptPath))
        {
            MtpGateReceiptWriter.Initialize(receiptPath);
        }

        // Preserve xUnit's internal automated-mode dispatch. Ordinary direct
        // execution uses MTP and its aggregate zero-test failure contract.
        if (global::System.Linq.Enumerable.Any(runArgs, arg => arg == "-automated" || arg == "@@"))
        {
            return global::Xunit.Runner.InProc.SystemConsole.ConsoleRunner
                .Run(runArgs)
                .GetAwaiter().GetResult();
        }

        return global::Xunit.MicrosoftTestingPlatform.TestPlatformTestFramework
            .RunAsync(runArgs, AddExtensions)
            .GetAwaiter().GetResult();
    }

    private static void AddExtensions(
        Microsoft.Testing.Platform.Builder.ITestApplicationBuilder builder,
        string[] args)
    {
        SelfRegisteredExtensions.AddSelfRegisteredExtensions(builder, args);

        string? receiptPath = Environment.GetEnvironmentVariable(
            MtpGateReceiptConsumer.ReceiptPathEnvironmentVariable);
        if (!string.IsNullOrWhiteSpace(receiptPath))
        {
            builder.TestHost.AddDataConsumer(
                _ => new MtpGateReceiptConsumer(receiptPath));
        }
    }
}
