<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="MarkdownTable.Formatting" Version="0.3.3" />
    <PackageVersion Include="Markout" Version="0.12.0" />
    <PackageVersion Include="ShellComplete" Version="0.1.0" />
    <PackageVersion Include="SourceLinkFetch" Version="0.1.0" />
    <PackageVersion Include="System.CommandLine" Version="2.0.5" />
    <PackageVersion Include="System.Security.Cryptography.Pkcs" Version="10.0.5" />
    <PackageVersion Include="System.Security.Cryptography.ProtectedData" Version="10.0.5" />
    <PackageVersion Include="xunit.v3" Version="3.2.2" />
  </ItemGroup>
</Project>
