using System.Text;
using System.Text.RegularExpressions;
using System.Xml;
using DotnetInspector.Metadata;

namespace DotnetInspector.Inspectors;

/// <summary>
/// Parses XML documentation files (.xml) that accompany .NET assemblies.
/// These files are generated by the compiler and contain structured documentation.
/// </summary>
public partial class XmlDocFileParser
{
    private readonly Dictionary<string, XmlNode> _members = new(StringComparer.Ordinal);
    private bool _loaded;

    /// <summary>
    /// Loads an XML documentation file.
    /// </summary>
    public bool Load(string xmlPath)
    {
        if (!File.Exists(xmlPath))
            return false;

        try
        {
            var doc = new XmlDocument();
            doc.Load(xmlPath);

            var members = doc.SelectNodes("/doc/members/member");
            if (members == null)
                return false;

            foreach (XmlNode member in members)
            {
                var name = member.Attributes?["name"]?.Value;
                if (name != null)
                {
                    _members[name] = member;
                }
            }

            _loaded = true;
            return true;
        }
        catch
        {
            return false;
        }
    }

    /// <summary>
    /// Gets documentation for a type.
    /// </summary>
    /// <param name="fullTypeName">Full type name including namespace (e.g., "System.Text.Json.JsonSerializer")</param>
    public DocCommentParser.DocComment? GetTypeDocumentation(string fullTypeName)
    {
        if (!_loaded)
            return null;

        // Handle generic types: convert List`1 to List{T} format used in XML docs
        var xmlKey = $"T:{ConvertToXmlDocName(fullTypeName)}";

        if (!_members.TryGetValue(xmlKey, out var node))
            return null;

        return ParseMemberNode(node);
    }

    /// <summary>
    /// Gets documentation for a member (method, property, field, event).
    /// </summary>
    /// <param name="fullTypeName">Full type name including namespace</param>
    /// <param name="memberName">Member name</param>
    /// <param name="memberKind">Member kind (method, property, field, event)</param>
    public DocCommentParser.DocComment? GetMemberDocumentation(string fullTypeName, string memberName, string? memberKind = null)
    {
        if (!_loaded)
            return null;

        var typeXmlName = ConvertToXmlDocName(fullTypeName);

        // Try different prefixes based on member kind
        string[] prefixes = memberKind switch
        {
            "method" => ["M"],
            "property" => ["P"],
            "field" => ["F"],
            "event" => ["E"],
            _ => ["M", "P", "F", "E"]  // Try all if unknown
        };

        // Handle constructors
        var xmlMemberName = memberName == ".ctor" ? "#ctor" : memberName;

        foreach (var prefix in prefixes)
        {
            // For methods, we need to handle overloads - try without parameters first
            var xmlKey = $"{prefix}:{typeXmlName}.{xmlMemberName}";

            if (_members.TryGetValue(xmlKey, out var node))
                return ParseMemberNode(node);

            // For methods, also search for any overload
            if (prefix == "M")
            {
                var matchingKey = _members.Keys
                    .FirstOrDefault(k => k.StartsWith($"{xmlKey}(", StringComparison.Ordinal) || k == xmlKey);

                if (matchingKey != null && _members.TryGetValue(matchingKey, out node))
                    return ParseMemberNode(node);
            }
        }

        return null;
    }

    /// <summary>
    /// Converts a CLR type name to XML documentation format.
    /// </summary>
    private static string ConvertToXmlDocName(string typeName)
    {
        // Handle nested types: Outer+Inner -> Outer.Inner
        typeName = typeName.Replace('+', '.');

        // Handle generic arity: List`1 stays as List`1 in XML docs
        return typeName;
    }

    /// <summary>
    /// Parses an XML member node into a DocComment.
    /// </summary>
    private DocCommentParser.DocComment? ParseMemberNode(XmlNode node)
    {
        string? summary = GetElementText(node, "summary");
        string? remarks = GetElementText(node, "remarks");
        string? returns = GetElementText(node, "returns");

        Dictionary<string, string>? parameters = null;
        var paramNodes = node.SelectNodes("param");
        if (paramNodes != null && paramNodes.Count > 0)
        {
            parameters = new Dictionary<string, string>();
            foreach (XmlNode param in paramNodes)
            {
                var name = param.Attributes?["name"]?.Value;
                if (name != null)
                {
                    parameters[name] = NormalizeWhitespace(GetNodeTextWithRefs(param));
                }
            }
        }

        // Extract sample references from <example><code source="..."/> elements
        List<DocCommentParser.SampleReference>? samples = ExtractSampleReferences(node);

        if (summary == null && remarks == null && returns == null && parameters == null && samples == null)
            return null;

        return new DocCommentParser.DocComment(summary, remarks, parameters, returns, samples);
    }

    private static string? GetElementText(XmlNode parent, string elementName)
    {
        var node = parent.SelectSingleNode(elementName);
        if (node == null)
            return null;

        var text = GetNodeTextWithRefs(node);
        text = NormalizeWhitespace(text);
        return string.IsNullOrWhiteSpace(text) ? null : text;
    }

    /// <summary>
    /// Recursively extracts text from a node, replacing see/paramref/typeparamref
    /// elements with their referenced names.
    /// </summary>
    private static string GetNodeTextWithRefs(XmlNode node)
    {
        var sb = new StringBuilder();

        foreach (XmlNode child in node.ChildNodes)
        {
            switch (child.NodeType)
            {
                case XmlNodeType.Text:
                case XmlNodeType.Whitespace:
                case XmlNodeType.SignificantWhitespace:
                    sb.Append(child.Value);
                    break;

                case XmlNodeType.Element:
                    switch (child.Name)
                    {
                        case "see":
                        case "seealso":
                            var cref = child.Attributes?["cref"]?.Value;
                            if (cref != null)
                            {
                                sb.Append(SimplifyTypeName(cref));
                            }
                            else
                            {
                                var innerText = child.InnerText;
                                if (!string.IsNullOrWhiteSpace(innerText))
                                {
                                    sb.Append(innerText);
                                }
                            }
                            break;

                        case "paramref":
                        case "typeparamref":
                            var name = child.Attributes?["name"]?.Value;
                            if (name != null)
                            {
                                sb.Append(name);
                            }
                            break;

                        case "c":
                            sb.Append(child.InnerText);
                            break;

                        default:
                            sb.Append(GetNodeTextWithRefs(child));
                            break;
                    }
                    break;
            }
        }

        return sb.ToString();
    }

    /// <summary>
    /// Simplifies a cref value to just the type/member name.
    /// </summary>
    private static string SimplifyTypeName(string cref)
    {
        // Remove type prefix (T:, M:, P:, F:, E:, N:)
        if (cref.Length > 2 && cref[1] == ':')
        {
            cref = cref[2..];
        }

        // Remove method parameters
        var parenIndex = cref.IndexOf('(');
        if (parenIndex > 0)
        {
            cref = cref[..parenIndex];
        }

        // Get just the last part (simple name)
        var lastDot = cref.LastIndexOf('.');
        if (lastDot >= 0)
        {
            cref = cref[(lastDot + 1)..];
        }

        // Handle generic arity (e.g., List`1 -> List)
        var backtick = cref.IndexOf('`');
        if (backtick >= 0)
        {
            cref = cref[..backtick];
        }

        return cref;
    }

    /// <summary>
    /// Extracts sample references from doc comments.
    /// </summary>
    private static List<DocCommentParser.SampleReference>? ExtractSampleReferences(XmlNode node)
    {
        List<DocCommentParser.SampleReference> samples = [];

        // Pattern: <example><code source="..." region="..." title="..."/></example>
        var codeNodes = node.SelectNodes("example/code[@source]");
        if (codeNodes != null)
        {
            foreach (XmlNode codeNode in codeNodes)
            {
                var source = codeNode.Attributes?["source"]?.Value;
                if (string.IsNullOrEmpty(source))
                    continue;

                var region = codeNode.Attributes?["region"]?.Value;
                var title = codeNode.Attributes?["title"]?.Value;

                samples.Add(new DocCommentParser.SampleReference(
                    NormalizePath(source),
                    title,
                    region
                ));
            }
        }

        return samples.Count > 0 ? samples : null;
    }

    private static string NormalizePath(string path) => path.Replace('\\', '/');

    [GeneratedRegex(@"\s+")]
    private static partial Regex WhitespaceRegex();

    private static string NormalizeWhitespace(string text) =>
        WhitespaceRegex().Replace(text.Trim(), " ");
}
