using System.Xml;
using ILInspector.Metadata;

namespace DotnetInspector.Inspectors;

/// <summary>
/// Parses XML documentation files (.xml) that accompany .NET assemblies.
/// These files are generated by the compiler and contain structured documentation.
/// </summary>
public class XmlDocFileParser
{
    private readonly Dictionary<string, XmlNode> _members = new(StringComparer.Ordinal);
    // Maps a member's base key (the doc key up to the first '(' or '`', e.g. "M:Ns.Type.Method")
    // to all full keys that share it (overloads, generic-arity variants). Lets overload lookups
    // scan only a member's own keys instead of every key in the file.
    private readonly Dictionary<string, List<string>> _membersByBaseKey = new(StringComparer.Ordinal);
    private bool _loaded;

    private static string BaseKey(string memberKey)
    {
        // Cut at the parameter list '(' or the method-arity marker "``" (double backtick), whichever
        // comes first. A single backtick is the enclosing type's arity (e.g. "List`1.Add") and must
        // stay in the base key, matching how the lookup keys are constructed.
        int paren = memberKey.IndexOf('(');
        int methodArity = memberKey.IndexOf("``", StringComparison.Ordinal);
        int cut = (paren, methodArity) switch
        {
            ( >= 0, >= 0) => Math.Min(paren, methodArity),
            ( >= 0, _) => paren,
            (_, >= 0) => methodArity,
            _ => -1,
        };
        return cut >= 0 ? memberKey[..cut] : memberKey;
    }

    private IEnumerable<string> CandidateKeys(string baseKey)
        => _membersByBaseKey.TryGetValue(baseKey, out var keys) ? keys : [];

    /// <summary>
    /// Loads an XML documentation file.
    /// </summary>
    public bool Load(string xmlPath)
    {
        if (!File.Exists(xmlPath))
            return false;

        try
        {
            var doc = DotnetInspector.Core.HardenedXml.LoadXmlDocument(xmlPath);

            var members = doc.SelectNodes("/doc/members/member");
            if (members == null)
                return false;

            foreach (XmlNode member in members)
            {
                var name = member.Attributes?["name"]?.Value;
                if (name != null)
                {
                    _members[name] = member;
                    var baseKey = BaseKey(name);
                    if (!_membersByBaseKey.TryGetValue(baseKey, out var keys))
                        _membersByBaseKey[baseKey] = keys = [];
                    keys.Add(name);
                }
            }

            _loaded = true;
            return true;
        }
        catch
        {
            return false;
        }
    }

    /// <summary>
    /// Gets documentation for a type.
    /// </summary>
    /// <param name="fullTypeName">Full type name including namespace (e.g., "System.Text.Json.JsonSerializer")</param>
    public DocCommentParser.DocComment? GetTypeDocumentation(string fullTypeName)
    {
        if (!_loaded)
            return null;

        // Handle generic types: convert List`1 to List{T} format used in XML docs
        var xmlKey = $"T:{ConvertToXmlDocName(fullTypeName)}";

        if (!_members.TryGetValue(xmlKey, out var node))
            return null;

        return ParseMemberNode(node);
    }

    /// <summary>
    /// Gets documentation for a member (method, property, field, event).
    /// </summary>
    /// <param name="fullTypeName">Full type name including namespace</param>
    /// <param name="memberName">Member name</param>
    /// <param name="memberKind">Member kind (method, property, field, event)</param>
    public DocCommentParser.DocComment? GetMemberDocumentation(string fullTypeName, string memberName, string? memberKind = null)
    {
        if (!_loaded)
            return null;

        var typeXmlName = ConvertToXmlDocName(fullTypeName);

        // Try different prefixes based on member kind
        string[] prefixes = memberKind switch
        {
            "method" => ["M"],
            "property" => ["P"],
            "field" => ["F"],
            "event" => ["E"],
            _ => ["M", "P", "F", "E"]  // Try all if unknown
        };

        // Handle constructors
        var xmlMemberName = memberName == ".ctor" ? "#ctor" : memberName;

        foreach (var prefix in prefixes)
        {
            // For methods, we need to handle overloads - try without parameters first
            var xmlKey = $"{prefix}:{typeXmlName}.{xmlMemberName}";

            if (_members.TryGetValue(xmlKey, out var node))
                return ParseMemberNode(node);

            // For methods, also search for any overload
            if (prefix == "M")
            {
                var matchingKey = CandidateKeys(xmlKey)
                    .FirstOrDefault(k => k.StartsWith($"{xmlKey}(", StringComparison.Ordinal) || k == xmlKey);

                if (matchingKey != null && _members.TryGetValue(matchingKey, out node))
                    return ParseMemberNode(node);
            }
        }

        return null;
    }

    public DocCommentParser.DocComment? GetMemberDocumentation(ApiType apiType, ApiMember member)
    {
        if (!_loaded)
            return null;

        if (ApiMemberIdentity.TryGetXmlDocMemberIdentity(apiType, member, out var identity))
            return GetMemberDocumentation(identity);

        var typeXmlName = ConvertToXmlDocName(apiType.FullName);
        var xmlMemberName = member.Name == ".ctor" ? "#ctor" : member.Name;
        var prefix = member.Kind switch
        {
            "property" => "P",
            "field" => "F",
            "event" => "E",
            _ => "M"
        };
        var xmlKey = $"{prefix}:{typeXmlName}.{xmlMemberName}";

        if (prefix != "M")
        {
            var nonMethodSignatureParameters = GetNormalizedSignatureParameters(member.Signature, EmptyTypeParameterMap, EmptyTypeParameterMap);
            if (nonMethodSignatureParameters.Count > 0)
            {
                var parameterizedCandidates = CandidateKeys(xmlKey)
                    .Where(k => k.StartsWith($"{xmlKey}(", StringComparison.Ordinal))
                    .ToList();
                var matchingKey = parameterizedCandidates.FirstOrDefault(key =>
                    TryGetXmlDocParameters(key, out var xmlParameters)
                    && ParametersMatch(nonMethodSignatureParameters, xmlParameters));
                return matchingKey != null && _members.TryGetValue(matchingKey, out var matchingNode)
                    ? ParseMemberNode(matchingNode)
                    : null;
            }

            return _members.TryGetValue(xmlKey, out var node)
                ? ParseMemberNode(node)
                : null;
        }

        var candidates = CandidateKeys(xmlKey)
            .Where(k =>
                k == xmlKey
                || k.StartsWith($"{xmlKey}(", StringComparison.Ordinal)
                || k.StartsWith($"{xmlKey}``", StringComparison.Ordinal))
            .ToList();
        if (candidates.Count == 0)
            return null;

        var typeParameterMap = apiType.TypeParameters
            .Select((p, i) => (p.Name, Index: i))
            .ToDictionary(p => p.Name, p => p.Index, StringComparer.Ordinal);
        var methodParameterMap = GetMethodGenericParameterMap(member.Signature, member.Name);
        var signatureParameters = GetNormalizedSignatureParameters(member.Signature, typeParameterMap, methodParameterMap);
        if (signatureParameters.Count > 0)
        {
            var matchingKey = candidates.FirstOrDefault(key =>
                TryGetXmlDocParameters(key, out var xmlParameters)
                && ParametersMatch(signatureParameters, xmlParameters));
            if (matchingKey != null && _members.TryGetValue(matchingKey, out var matchingNode))
                return ParseMemberNode(matchingNode);

            return null;
        }

        var fallbackKey = candidates.FirstOrDefault(key => key == xmlKey)
            ?? candidates.FirstOrDefault();
        return fallbackKey != null && _members.TryGetValue(fallbackKey, out var fallbackNode)
            ? ParseMemberNode(fallbackNode)
            : null;
    }

    private DocCommentParser.DocComment? GetMemberDocumentation(ApiMemberIdentity.XmlDocMemberIdentity identity)
    {
        var xmlKey = identity.LookupKey;
        var prefix = xmlKey.Length > 0 ? xmlKey[0].ToString() : "";

        if (prefix != "M")
        {
            if (identity.NormalizedParameters.Count > 0)
            {
                var parameterizedCandidates = CandidateKeys(xmlKey)
                    .Where(k => k.StartsWith($"{xmlKey}(", StringComparison.Ordinal))
                    .ToList();
                var matchingKey = parameterizedCandidates.FirstOrDefault(key =>
                    TryGetXmlDocParameters(key, out var xmlParameters)
                    && ParametersMatch(identity.NormalizedParameters, xmlParameters));
                return matchingKey != null && _members.TryGetValue(matchingKey, out var matchingNode)
                    ? ParseMemberNode(matchingNode)
                    : null;
            }

            return _members.TryGetValue(xmlKey, out var node)
                ? ParseMemberNode(node)
                : null;
        }

        var candidates = CandidateKeys(xmlKey)
            .Where(k =>
                k == xmlKey
                || k.StartsWith($"{xmlKey}(", StringComparison.Ordinal)
                || k.StartsWith($"{xmlKey}``", StringComparison.Ordinal))
            .ToList();
        if (candidates.Count == 0)
            return null;

        if (identity.NormalizedParameters.Count > 0)
        {
            var matchingKey = candidates.FirstOrDefault(key =>
                TryGetXmlDocParameters(key, out var xmlParameters)
                && ParametersMatch(identity.NormalizedParameters, xmlParameters));
            if (matchingKey != null && _members.TryGetValue(matchingKey, out var matchingNode))
                return ParseMemberNode(matchingNode);

            return null;
        }

        var fallbackKey = candidates.FirstOrDefault(key => key == xmlKey)
            ?? candidates.FirstOrDefault();
        return fallbackKey != null && _members.TryGetValue(fallbackKey, out var fallbackNode)
            ? ParseMemberNode(fallbackNode)
            : null;
    }

    private static List<string> GetNormalizedSignatureParameters(
        string? signature,
        IReadOnlyDictionary<string, int> typeParameterMap,
        IReadOnlyDictionary<string, int> methodParameterMap)
    {
        var paramList = SignatureParser.ExtractParamList(signature);
        if (string.IsNullOrEmpty(paramList) && !string.IsNullOrEmpty(signature))
        {
            var indexerStart = signature.IndexOf("this[", StringComparison.Ordinal);
            if (indexerStart >= 0)
            {
                var bracketStart = indexerStart + "this".Length;
                var bracketEnd = signature.IndexOf(']', bracketStart);
                if (bracketEnd > bracketStart)
                    paramList = $"({signature[(bracketStart + 1)..bracketEnd]})";
            }
        }
        if (string.IsNullOrEmpty(paramList))
            return [];

        var inner = paramList.Trim();
        if (inner.StartsWith('(') && inner.EndsWith(')'))
            inner = inner[1..^1];
        if (string.IsNullOrWhiteSpace(inner))
            return [];

        return SplitParameters(inner)
            .Select(p => NormalizeParameterType(p, typeParameterMap, methodParameterMap))
            .ToList();
    }

    private static bool TryGetXmlDocParameters(string key, out List<string> parameters)
    {
        parameters = [];
        var parenStart = key.IndexOf('(');
        var parenEnd = key.LastIndexOf(')');
        if (parenStart < 0 || parenEnd <= parenStart)
            return false;

        var inner = key[(parenStart + 1)..parenEnd];
        parameters = string.IsNullOrWhiteSpace(inner)
            ? []
            : SplitParameters(inner)
                .Select(ApiMemberIdentity.NormalizeXmlDocParameterType)
                .ToList();
        return true;
    }

    private static bool ParametersMatch(IReadOnlyList<string> signatureParameters, IReadOnlyList<string> xmlParameters)
    {
        if (signatureParameters.Count != xmlParameters.Count)
            return false;

        for (var i = 0; i < signatureParameters.Count; i++)
        {
            var left = signatureParameters[i];
            var right = xmlParameters[i];
            if (left == "*" || right == "*")
                continue;
            if (!string.Equals(left, right, StringComparison.Ordinal))
                return false;
        }

        return true;
    }

    private static List<string> SplitParameters(string parameters)
    {
        List<string> result = [];
        var depth = 0;
        var lastSplit = 0;
        for (var i = 0; i < parameters.Length; i++)
        {
            var c = parameters[i];
            if (c is '<' or '{' or '(')
                depth++;
            else if (c is '>' or '}' or ')')
                depth--;
            else if (c == ',' && depth == 0)
            {
                result.Add(parameters[lastSplit..i].Trim());
                lastSplit = i + 1;
            }
        }

        result.Add(parameters[lastSplit..].Trim());
        return result;
    }

    private static readonly IReadOnlyDictionary<string, int> EmptyTypeParameterMap =
        new Dictionary<string, int>(StringComparer.Ordinal);

    private static Dictionary<string, int> GetMethodGenericParameterMap(string? signature, string memberName)
    {
        if (string.IsNullOrWhiteSpace(signature) || string.IsNullOrWhiteSpace(memberName))
            return new Dictionary<string, int>(StringComparer.Ordinal);

        var parenStart = signature.IndexOf('(');
        if (parenStart <= 0)
            return new Dictionary<string, int>(StringComparer.Ordinal);

        var nameIndex = signature.LastIndexOf(memberName, parenStart - 1, StringComparison.Ordinal);
        if (nameIndex < 0)
            return new Dictionary<string, int>(StringComparer.Ordinal);

        var genericStart = nameIndex + memberName.Length;
        if (genericStart >= parenStart || signature[genericStart] != '<')
            return new Dictionary<string, int>(StringComparer.Ordinal);

        if (!TryGetGenericParts(signature[genericStart..parenStart], 0, out _, out var parameters))
            return new Dictionary<string, int>(StringComparer.Ordinal);

        return SplitParameters(parameters)
            .Select((name, index) => (Name: name.Trim(), Index: index))
            .Where(p => p.Name.Length > 0)
            .ToDictionary(p => p.Name, p => p.Index, StringComparer.Ordinal);
    }

    private static string NormalizeParameterType(
        string parameter,
        IReadOnlyDictionary<string, int> typeParameterMap,
        IReadOnlyDictionary<string, int> methodParameterMap)
    {
        var type = SignatureParser.ExtractParamType(parameter.Trim());
        foreach (var prefix in new[] { "ref ", "out ", "in ", "params ", "this " })
        {
            if (type.StartsWith(prefix, StringComparison.Ordinal))
            {
                type = type[prefix.Length..].TrimStart();
                break;
            }
        }

        type = type.TrimEnd('@');
        type = RemoveNullableAnnotations(type);

        if (TryNormalizeGenericParameterReference(type, typeParameterMap, methodParameterMap, out var genericParameter))
            return genericParameter;

        if (type.EndsWith("[]", StringComparison.Ordinal))
            return $"{NormalizeParameterType(type[..^2], typeParameterMap, methodParameterMap)}[]";

        var genericStart = IndexOfAny(type, '<', '{');
        if (genericStart >= 0 && TryGetGenericParts(type, genericStart, out var genericType, out var genericArgs))
        {
            var normalizedType = NormalizeSimpleTypeName(genericType);
            var normalizedArgs = SplitParameters(genericArgs)
                .Select(p => NormalizeParameterType(p, typeParameterMap, methodParameterMap));
            return $"{normalizedType}{{{string.Join(",", normalizedArgs)}}}";
        }

        return NormalizeSimpleTypeName(type);
    }

    private static string NormalizeSimpleTypeName(string type) => PrimitiveTypeNames.ToClrFullName(type);

    private static string RemoveNullableAnnotations(string type)
        => type.Replace("?", "", StringComparison.Ordinal);

    private static bool TryGetGenericParts(string type, int genericStart, out string genericType, out string genericArgs)
    {
        genericType = type[..genericStart];
        genericArgs = "";

        var open = type[genericStart];
        var close = open == '<' ? '>' : '}';
        var depth = 0;
        for (var i = genericStart; i < type.Length; i++)
        {
            var c = type[i];
            if (c == open)
                depth++;
            else if (c == close)
            {
                depth--;
                if (depth == 0)
                {
                    genericArgs = type[(genericStart + 1)..i];
                    return true;
                }
            }
        }

        return false;
    }

    private static bool TryNormalizeGenericParameterReference(
        string type,
        IReadOnlyDictionary<string, int> typeParameterMap,
        IReadOnlyDictionary<string, int> methodParameterMap,
        out string normalized)
    {
        normalized = "";
        if (type.StartsWith("``", StringComparison.Ordinal) && int.TryParse(type[2..], out var methodIndex))
        {
            normalized = $"M{methodIndex}";
            return true;
        }

        if (type.StartsWith('`') && int.TryParse(type[1..], out var typeIndex))
        {
            normalized = $"T{typeIndex}";
            return true;
        }

        if (methodParameterMap.TryGetValue(type, out methodIndex))
        {
            normalized = $"M{methodIndex}";
            return true;
        }

        if (typeParameterMap.TryGetValue(type, out typeIndex))
        {
            normalized = $"T{typeIndex}";
            return true;
        }

        return false;
    }

    private static int IndexOfAny(string value, char first, char second)
    {
        var firstIndex = value.IndexOf(first);
        var secondIndex = value.IndexOf(second);
        return (firstIndex, secondIndex) switch
        {
            (< 0, < 0) => -1,
            (< 0, _) => secondIndex,
            (_, < 0) => firstIndex,
            _ => Math.Min(firstIndex, secondIndex)
        };
    }

    /// <summary>
    /// Converts a CLR type name to XML documentation format.
    /// </summary>
    private static string ConvertToXmlDocName(string typeName)
    {
        // Handle nested types: Outer+Inner -> Outer.Inner
        typeName = typeName.Replace('+', '.');

        // Handle generic arity: List`1 stays as List`1 in XML docs
        return typeName;
    }

    /// <summary>
    /// Parses an XML member node into a DocComment.
    /// </summary>
    private DocCommentParser.DocComment? ParseMemberNode(XmlNode node)
    {
        string? summary = GetElementText(node, "summary");
        string? remarks = GetElementText(node, "remarks");
        string? returns = GetElementText(node, "returns");

        Dictionary<string, string>? parameters = null;
        var paramNodes = node.SelectNodes("param");
        if (paramNodes != null && paramNodes.Count > 0)
        {
            parameters = new Dictionary<string, string>();
            foreach (XmlNode param in paramNodes)
            {
                var name = param.Attributes?["name"]?.Value;
                if (name != null)
                {
                    parameters[name] = XmlDocText.NormalizeWhitespace(XmlDocText.GetNodeTextWithRefs(param));
                }
            }
        }

        // Extract sample references from <example><code source="..."/> elements
        List<DocCommentParser.SampleReference>? samples = ExtractSampleReferences(node);

        if (summary == null && remarks == null && returns == null && parameters == null && samples == null)
            return null;

        return new DocCommentParser.DocComment(summary, remarks, parameters, returns, samples);
    }

    private static string? GetElementText(XmlNode parent, string elementName)
    {
        var node = parent.SelectSingleNode(elementName);
        if (node == null)
            return null;

        var text = XmlDocText.NormalizeWhitespace(XmlDocText.GetNodeTextWithRefs(node));
        return string.IsNullOrWhiteSpace(text) ? null : text;
    }

    /// <summary>
    /// Extracts sample references from doc comments.
    /// </summary>
    private static List<DocCommentParser.SampleReference>? ExtractSampleReferences(XmlNode node)
    {
        List<DocCommentParser.SampleReference> samples = [];

        // Pattern: <example><code source="..." region="..." title="..."/></example>
        var codeNodes = node.SelectNodes("example/code[@source]");
        if (codeNodes != null)
        {
            foreach (XmlNode codeNode in codeNodes)
            {
                var source = codeNode.Attributes?["source"]?.Value;
                if (string.IsNullOrEmpty(source))
                    continue;

                var region = codeNode.Attributes?["region"]?.Value;
                var title = codeNode.Attributes?["title"]?.Value;

                samples.Add(new DocCommentParser.SampleReference(
                    XmlDocText.NormalizePath(source),
                    title,
                    region
                ));
            }
        }

        return samples.Count > 0 ? samples : null;
    }

}
