<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>$(DefaultTargetFramework)</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>preview</LangVersion>
  </PropertyGroup>

  <PropertyGroup>
    <Authors>Richard Lander</Authors>
    <Description>A library for downloading and extracting NuGet packages</Description>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DotnetInspector.Core\DotnetInspector.Core.csproj" />
    <ProjectReference Include="..\NuGetFetch\NuGetFetch.csproj" />
    <PackageReference Include="NuGet.Versioning" />
    <InternalsVisibleTo Include="DotnetInspector.Services.Tests" />
    <InternalsVisibleTo Include="dotnet-inspect.Tests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Security.Cryptography.ProtectedData" />
  </ItemGroup>

</Project>
