<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>$(DefaultTargetFramework)</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>preview</LangVersion>
  </PropertyGroup>

  <PropertyGroup>
    <Authors>Richard Lander</Authors>
    <Description>A library for downloading and extracting NuGet packages</Description>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DotnetInspector.Core\DotnetInspector.Core.csproj" />
    <PackageReference Include="NuGetFetch" Version="0.4.0" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="9.0.4" />
  </ItemGroup>

</Project>
