using DotnetInspector.Models;
using DotnetInspector.Views;
using DotnetInspector.Packages;
using Markout;

namespace DotnetInspector;

[MarkoutContextOptions(SuppressTableWarnings = true)]
[MarkoutContext(typeof(InspectionResultView))]
[MarkoutContext(typeof(LibraryInspectionView))]
[MarkoutContext(typeof(LibraryInspectionReport))]
[MarkoutContext(typeof(ReferenceRow))]
[MarkoutContext(typeof(ExtensionMethodRow))]
[MarkoutContext(typeof(ClassifiedMethodRow))]
[MarkoutContext(typeof(PInvokeMethodRow))]
[MarkoutContext(typeof(ResourceRow))]
[MarkoutContext(typeof(CustomAttributeRow))]
[MarkoutContext(typeof(TypeForwarderRow))]
[MarkoutContext(typeof(CliApiSurface))]
[MarkoutContext(typeof(TypeView))]
[MarkoutContext(typeof(MemberCodeView))]
[MarkoutContext(typeof(TypeSummaryRow))]
[MarkoutContext(typeof(ForwarderSummaryRow))]
[MarkoutContext(typeof(MemberRow))]
[MarkoutContext(typeof(MethodAttributeRow))]
[MarkoutContext(typeof(ConstructorOverloadView))]
[MarkoutContext(typeof(ConstructorParameterRow))]
[MarkoutContext(typeof(EnumValueRow))]
[MarkoutContext(typeof(TypeParameterRow))]
[MarkoutContext(typeof(InterfaceRow))]
[MarkoutContext(typeof(BaseclassRow))]
[MarkoutContext(typeof(DependencyGroup))]
[MarkoutContext(typeof(PackageDependency))]
[MarkoutContext(typeof(FlatDependency))]
[MarkoutContext(typeof(RidPackageReferenceView))]
[MarkoutContext(typeof(ImplementsResultView))]
[MarkoutContext(typeof(ImplementerRow))]
[MarkoutContext(typeof(FindResultView))]
[MarkoutContext(typeof(FindRow))]
[MarkoutContext(typeof(ExtensionsResultView))]
[MarkoutContext(typeof(ExtensionCountRow))]
[MarkoutContext(typeof(ExtensionRow))]
[MarkoutContext(typeof(DiffOneLineView))]
[MarkoutContext(typeof(DiffOneLineRow))]
[MarkoutContext(typeof(DiffFullView))]
[MarkoutContext(typeof(DiffChangeRow))]
[MarkoutContext(typeof(ApiTypeOneLineView))]
[MarkoutContext(typeof(ApiOneLineRow))]
[MarkoutContext(typeof(ApiSurfaceOneLineView))]
[MarkoutContext(typeof(ApiSurfaceOneLineRow))]
[MarkoutContext(typeof(SamplesListView))]
[MarkoutContext(typeof(SampleRow))]
[MarkoutContext(typeof(EmptyDepsView))]
public partial class MarkoutContext : MarkoutSerializerContext
{
}
