<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>$(DefaultTargetFramework)</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>preview</LangVersion>
    <IsAotCompatible>true</IsAotCompatible>
  </PropertyGroup>

  <PropertyGroup>
    <Authors>Richard Lander</Authors>
    <Description>HTTP composition and request telemetry for dotnet-inspect</Description>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="DotnetInspector.Cache" />
    <InternalsVisibleTo Include="DotnetInspector.Core" />
    <InternalsVisibleTo Include="DotnetInspector.Networking.Tests" />
    <InternalsVisibleTo Include="DotnetInspector.Packages" />
    <InternalsVisibleTo Include="DotnetInspector.Services.Tests" />
    <InternalsVisibleTo Include="DotnetInspect.Cli.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\InertText\InertText.csproj" />
    <ProjectReference Include="..\NetworkAccess\NetworkAccess.csproj" />
  </ItemGroup>
</Project>
