<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>preview</LangVersion>
  </PropertyGroup>

  <PropertyGroup>
    <Authors>Richard Lander</Authors>
    <Description>A library for inspecting .NET assembly metadata</Description>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="dotnet-inspect" />
    <InternalsVisibleTo Include="dotnet-inspect.Tests" />
    <InternalsVisibleTo Include="DotnetInspector.Metadata.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DotnetInspector.Core\DotnetInspector.Core.csproj" />
  </ItemGroup>

  <!-- System.Reflection.Metadata is part of net10.0 BCL -->

</Project>
