<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>$(DefaultTargetFramework)</TargetFramework>
    <LangVersion>preview</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <IsAotCompatible>false</IsAotCompatible>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/DotnetInspector.MetadataRendering/DotnetInspector.MetadataRendering.csproj" />
    <ProjectReference Include="../../src/mdi/mdi.csproj" />
    <ProjectReference Include="../../src/ILInspector.Metadata/ILInspector.Metadata.csproj" />
  </ItemGroup>

</Project>
