<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net6.0;net8.0;net9.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsAotCompatible>false</IsAotCompatible>
    <CheckEolTargetFramework>false</CheckEolTargetFramework>
    <ManagePackageVersionsCentrally>false</ManagePackageVersionsCentrally>
    <OwnsItsOwnStderr>true</OwnsItsOwnStderr>
    <RestoreSources>../feed;https://api.nuget.org/v3/index.json</RestoreSources>
    <RestorePackagesPath>../packages</RestorePackagesPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="EmptyCompileGroup.Oracle" Version="[1.0.0]" />
  </ItemGroup>
</Project>
