<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>$(DefaultTargetFramework)</TargetFramework>
    <AssemblyName>DotnetInspector.CallerBinding.Facade</AssemblyName>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="../../services/DotnetInspector.Services.RouteLearning.Base/Middle.cs" Link="Middle.cs" />
  </ItemGroup>

</Project>
