<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>$(DefaultTargetFramework)</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>preview</LangVersion>
  </PropertyGroup>

  <PropertyGroup>
    <Authors>Richard Lander</Authors>
    <Description>IL-to-C# decompiler built on algorithms ported from dotnet/runtime</Description>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="ILInspector.Decompiler.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ILInspector.Metadata\ILInspector.Metadata.csproj" />
  </ItemGroup>

</Project>
