<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>$(DefaultTargetFramework)</TargetFramework>
    <LangVersion>preview</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <EnablePreviewFeatures>true</EnablePreviewFeatures>
    <IsPackable>false</IsPackable>
    <AssemblyName>analysis-harness</AssemblyName>
    <RootNamespace>ILInspector.AnalysisHarness</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/ILInspector.Analysis/ILInspector.Analysis.csproj" />
  </ItemGroup>

</Project>
