<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>$(DefaultTargetFramework)</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>preview</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../DotnetInspector.Packages/DotnetInspector.Packages.csproj" />
    <ProjectReference Include="../DotnetInspector.Platforms/DotnetInspector.Platforms.csproj" />
    <ProjectReference Include="../ILInspector.Metadata/ILInspector.Metadata.csproj" />
    <ProjectReference Include="../NuGetFetch/NuGetFetch.csproj" />
  </ItemGroup>

</Project>
