#!/usr/bin/env bash
# Regenerates prototypes/inspect-web/src/inspect-web-engine.d.ts (Vite-bundled type-only surface)
# and prototypes/inspect-web/engine/wwwroot/inspect-web-engine.js (the runtime wasm bootstrap
# module, served directly next to _framework/ by the wasm host — NOT Vite-bundled) from
# InspectWeb.Engine.dll's [JSExport] surface via tsbindgen.
#
# inspect-web-engine.js is the runtime wasm bootstrap plus one typed wrapper per
# [JSExport] export (dotnet.create()/getAssemblyExports(), then JSON.parse for
# any wire-shaped return). It generates from the exact same JsExportSurface as
# the .d.ts, so the two files cannot independently drift from each other the
# way a hand-maintained shim like engine.js could. It lives in engine/wwwroot
# specifically because its "./_framework/dotnet.js" import is relative to the
# wasm host's own served root, which only exists there (dev server and Vite
# build have no _framework/ under src/).
#
# Requires prototypes/inspect-web's frontend bundle (npm ci && npm run build)
# to already exist, since InspectWeb.Engine.csproj's own build validates it.
#
# Usage:
#   eng/generate-inspect-web-engine-dts.sh            # writes the committed files
#   eng/generate-inspect-web-engine-dts.sh --check     # fails if they would change (CI gate)
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
engine_csproj="$repo_root/prototypes/inspect-web/engine/InspectWeb.Engine.csproj"
engine_dll="$repo_root/prototypes/inspect-web/engine/bin/Release/net11.0/InspectWeb.Engine.dll"
dts_output_file="$repo_root/prototypes/inspect-web/src/inspect-web-engine.d.ts"
js_output_file="$repo_root/prototypes/inspect-web/engine/wwwroot/inspect-web-engine.js"
header_file="$(mktemp)"
dts_generated_file="$(mktemp)"
js_generated_file="$(mktemp)"
trap 'rm -f "$header_file" "$dts_generated_file" "$js_generated_file" "$dts_generated_file.body"' EXIT

cat > "$header_file" <<'EOF'
// GENERATED FILE — DO NOT EDIT BY HAND.
//
// Generated by tsbindgen from InspectWeb.Engine.dll's [JSExport] surface. Regenerate with:
//   eng/generate-inspect-web-engine-dts.sh
// CI fails if the committed file drifts from this output.

EOF

dotnet build "$engine_csproj" -c Release >&2
dotnet run --project "$repo_root/src/tsbindgen" -c Release -- "$engine_dll" \
  --emit-js "$js_generated_file.body" > "$dts_generated_file.body"
cat "$header_file" "$dts_generated_file.body" > "$dts_generated_file"
cat "$header_file" "$js_generated_file.body" > "$js_generated_file"

if [[ "${1:-}" == "--check" ]]; then
  drifted=0
  for pair in "$dts_generated_file:$dts_output_file" "$js_generated_file:$js_output_file"; do
    generated="${pair%%:*}"
    committed="${pair##*:}"
    if ! diff -q "$generated" "$committed" > /dev/null 2>&1; then
      echo "error: $committed is stale. Run eng/generate-inspect-web-engine-dts.sh and commit the result." >&2
      diff "$committed" "$generated" >&2 || true
      drifted=1
    fi
  done
  if [[ "$drifted" != 0 ]]; then
    exit 1
  fi
  echo "inspect-web-engine.d.ts and inspect-web-engine.js are up to date."
else
  cp "$dts_generated_file" "$dts_output_file"
  cp "$js_generated_file" "$js_output_file"
  echo "Wrote $dts_output_file"
  echo "Wrote $js_output_file"
fi
