<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>$(DefaultTargetFramework)</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>preview</LangVersion>
    <IsPackable>false</IsPackable>
    <IsAotCompatible>false</IsAotCompatible>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <NoWarn>$(NoWarn);CA1416</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../../src/InertText/InertText.csproj" />
    <ProjectReference Include="../../../src/TsJsExport.Contracts/TsJsExport.Contracts.csproj" />
  </ItemGroup>

</Project>
