<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>$(DefaultTargetFramework)</TargetFramework>
    <AssemblyName>ILInspector.Metadata.SpellabilityConsumer</AssemblyName>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../SignatureSpellabilityReference/ILInspector.Metadata.SpellabilityReference.csproj" />
  </ItemGroup>
</Project>
