<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>$(DefaultTargetFramework)</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>preview</LangVersion>
    <IsAotCompatible>true</IsAotCompatible>
  </PropertyGroup>

  <PropertyGroup>
    <Authors>Richard Lander</Authors>
    <Description>A lightweight NuGet client for downloading and extracting NuGet packages</Description>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NuGet.Versioning" />
    <PackageReference Include="System.Security.Cryptography.Pkcs" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="trustedroots/codesignctl.pem" LogicalName="codesignctl.pem" />
    <EmbeddedResource Include="trustedroots/timestampctl.pem" LogicalName="timestampctl.pem" />
  </ItemGroup>

</Project>
