using ILInspector.Decompiler.Tests.Gating;

namespace ILInspector.Decompiler.Tests;

/// <summary>
/// Custom entry point for the decompiler test executable.
/// </summary>
/// <remarks>
/// <para>
/// The auto-generated xUnit v3 entry point is disabled
/// (<c>&lt;XunitAutoGeneratedEntryPoint&gt;false&lt;/XunitAutoGeneratedEntryPoint&gt;</c>
/// in the project file) so we can pre-process a discoverable
/// <c>--gate &lt;preset&gt;</c> flag before delegating to the runner. Presets
/// wrap the <c>Speed</c>/<c>Area</c> trait taxonomy documented in
/// <c>docs/decompiler-correctness-pipeline.md</c> so callers and CI can bound
/// which gates run (notably skipping the multi-hour <c>Corpus</c> sweep)
/// without memorizing <c>-trait</c>/<c>-trait-</c> incantations.
/// </para>
/// <para>
/// Everything after the <c>--gate</c> handling mirrors the xUnit v3
/// auto-generated entry point verbatim, so Microsoft Testing Platform server
/// mode and the console runner behave exactly as before.
/// </para>
/// </remarks>
internal static class Program
{
    // Presets over the Speed/Area traits. Order matches --gate list output.
    // internal so GateExpectedClassesTests can assert the pre-merge preset and
    // eng/decompiler-gate-expected-classes.txt name the same classes.
    internal static readonly IReadOnlyList<GatePreset> Presets =
    [
        new("all", "Every test, including all slow gates (default with no --gate)."),
        new("fast", "Skip every slow gate (fast unit lane; matches the PR CI test job).", "-trait-", "Speed=Slow"),
        new("slow", "Only the slow gates.", "-trait", "Speed=Slow"),
        new("no-corpus", "Everything except the multi-hour Corpus sweep.", "-trait-", "Area=Corpus"),
        new(
            "pre-merge",
            "The docket and tractable fidelity gates (matches the PR CI decompiler-gates job).",
            "-class", "ILInspector.Decompiler.Tests.FidelityGateTests",
            "-class", "ILInspector.Decompiler.Tests.LoweredFidelityGateTests",
            "-class", "ILInspector.Decompiler.Tests.ByteNeutralityGateTests",
            "-class", "ILInspector.Decompiler.Tests.ClusterCaptureTests",
            "-class", "ILInspector.Decompiler.Tests.PrinterPrecedenceTests",
            "-class", "ILInspector.Decompiler.Tests.DiffFixtureFidelityTests",
            "-class", "ILInspector.Decompiler.Tests.NestedTargetLookupTests",
            "-class", "ILInspector.DecompilerHarness.AuthoredRebuildFidelityTests",
            "-class", "ILInspector.Decompiler.Tests.AnnotatedCompileBackFailureTests",
            // The gate's own plumbing guard rides along in the preset it guards.
            // Running it as a separate CI step was vacuous: a filter naming a
            // renamed or deleted class discovers nothing and exits 0. Inside the
            // preset it is covered by the same discovery/coverage checks as the
            // correctness gates, so it cannot silently stop running.
            "-class", "ILInspector.Decompiler.Tests.GateExpectedClassesTests"),
        new("corpus", "Only the Corpus area (the multi-hour sweep).", "-trait", "Area=Corpus"),
        new("roundtrip", "Only the RoundTrip area (compile-back / ReturnToSender).", "-trait", "Area=RoundTrip"),
        new("fidelity", "Only the Fidelity area.", "-trait", "Area=Fidelity"),
        new("validity", "Only the Validity area.", "-trait", "Area=Validity"),
    ];

    public static int Main(string[] args)
    {
        GateExpansion expansion = GateArgumentExpander.Expand(args, Presets);
        switch (expansion.Outcome)
        {
            case GateOutcome.Help:
                Console.Out.WriteLine(expansion.Message);
                return 0;
            case GateOutcome.Error:
                Console.Error.WriteLine(expansion.Message);
                return 2;
        }

        string[] runArgs = expansion.Args as string[] ?? expansion.Args.ToArray();

        // Mirror the xUnit v3 auto-generated entry point: honor the Microsoft
        // Testing Platform server handshake, otherwise use the console runner.
        if (global::System.Linq.Enumerable.Any(runArgs, arg => arg == "--server" || arg == "--internal-msbuild-node"))
        {
            return global::Xunit.MicrosoftTestingPlatform.TestPlatformTestFramework
                .RunAsync(runArgs, SelfRegisteredExtensions.AddSelfRegisteredExtensions)
                .GetAwaiter().GetResult();
        }

        return global::Xunit.Runner.InProc.SystemConsole.ConsoleRunner
            .Run(runArgs)
            .GetAwaiter().GetResult();
    }
}
