<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>$(DefaultTargetFramework)</TargetFramework>
    <LangVersion>preview</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsAotCompatible>false</IsAotCompatible>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ILInspector.Analysis.AsyncSiblingFriendBaseFixtures\ILInspector.Analysis.AsyncSiblingFriendBaseFixtures.csproj" />
  </ItemGroup>

</Project>
