using System.Xml.Linq;

namespace DotnetInspector.Tests;

/// <summary>
/// What this repository permits SDK pack and publish commands to produce
/// (#3330). Only tools are packable or publishable, and those must be project
/// properties rather than consequences of the invocation. Before the packaging
/// default was inverted, packing the solution emitted packages for internal
/// libraries and a benchmark fixture, all at
/// <c>1.0.0</c>, for code with no versioning story and no intent to be consumed
/// externally. A library that reaches a feed turns the layering rules in
/// <c>AGENTS.md</c> into an external compatibility surface instead of an
/// internal design constraint.
/// <para>
/// The enforcement is the root <c>Directory.Build.props</c>: with
/// <c>IsPackable=false</c> and <c>IsPublishable=false</c> inherited, a new
/// project participates in neither SDK surface. These tests hold both defaults,
/// the shared tool behavior, and the tool census together. They also give review
/// a local answer to "can this library's public API break anyone?", which on
/// #3306 had to be settled by reading two workflow files.
/// </para>
/// </summary>
public sealed class PackagingSurfaceTests
{
    static readonly string[] ToolProjects =
    [
        "src/dotnet-inspect/dotnet-inspect.csproj",
        "src/mdi/mdi.csproj",
        "src/runfaster/runfaster.csproj",
    ];

    /// <summary>
    /// The tool-project census. All and only the CLI projects declare
    /// <c>IsTool</c>, <c>IsPackable</c>, and <c>PackAsTool</c>. The first controls
    /// shared publish behavior; the packaging properties stay project-local
    /// because SDK runtime-identifier inference consumes <c>PackAsTool</c> before
    /// <c>Directory.Build.targets</c> is imported.
    /// </summary>
    [Fact]
    public void OnlyCliProjectsOptIntoToolDefaults()
    {
        var (tools, scanned) = ScanProjectsForProperty("IsTool");

        Assert.True(scanned > 0, "Scanned no project files; the census would pass vacuously.");
        Assert.Equal(ToolProjects.OrderBy(static p => p, StringComparer.Ordinal).ToArray(), tools);

        var (packAsTools, _) = ScanProjectsForProperty("PackAsTool");
        Assert.Equal(ToolProjects.OrderBy(static p => p, StringComparer.Ordinal).ToArray(), packAsTools);

        var (packableTools, _) = ScanProjectsForProperty("IsPackable");
        Assert.Equal(ToolProjects.OrderBy(static p => p, StringComparer.Ordinal).ToArray(), packableTools);
    }

    /// <summary>
    /// The gate for shared tool publish behavior: tools participate in solution
    /// publish, and their output carries no API-documentation sidecars, including
    /// documentation generated by referenced libraries.
    /// </summary>
    [Fact]
    public void ToolDefaultsAreCentralized()
    {
        string root = FindRepositoryRoot();
        var targets = XDocument.Load(Path.Combine(root, "Directory.Build.targets"));
        var toolGroup = Assert.Single(
            targets.Descendants(),
            static element => element.Name.LocalName == "PropertyGroup"
                && string.Equals(
                    element.Attribute("Condition")?.Value,
                    "'$(IsTool)' == 'true'",
                    StringComparison.Ordinal));

        AssertProperty(toolGroup, "PublishDocumentationFiles", "false");
        AssertProperty(toolGroup, "PublishDocumentationFile", "false");
        AssertProperty(toolGroup, "PublishReferencesDocumentationFiles", "false");
        AssertProperty(toolGroup, "IsPublishable", "true");
    }

    /// <summary>
    /// The half that keeps the tool census above from passing vacuously in the way
    /// that actually matters. Deleting the default restores the SDK's
    /// <c>IsPackable=true</c> for every project, at which point no project needs
    /// an opt-in and <see cref="OnlyCliProjectsOptIntoToolDefaults"/> still
    /// reports green while unintended library packages come back. An
    /// unconditional declaration is required for the same reason: a condition
    /// that stops holding is indistinguishable from the property being gone.
    /// </summary>
    [Fact]
    public void PackagingIsOffByDefaultForEveryProject()
    {
        AssertShippingPropertyIsOffByDefault("IsPackable");
    }

    [Fact]
    public void PublishingIsOffByDefaultForEveryProject()
    {
        AssertShippingPropertyIsOffByDefault("IsPublishable");
    }

    /// <summary>
    /// xUnit v3 projects are executable test hosts, not ordinary applications.
    /// The explicit metadata keeps SDK tooling from treating them as product
    /// executables and pins the repository to the current xUnit v3 project shape.
    /// </summary>
    [Fact]
    public void XunitProjectsDeclareExecutableTestMetadata()
    {
        string root = FindRepositoryRoot();
        var projects = EnumerateRepositoryProjects(root)
            .Select(path => (Path: path, Project: XDocument.Load(path)))
            .Where(static item => item.Project
                .Descendants()
                .Any(static element => element.Name.LocalName == "PackageReference"
                    && string.Equals(
                        element.Attribute("Include")?.Value,
                        "xunit.v3",
                        StringComparison.OrdinalIgnoreCase)))
            .ToArray();

        Assert.NotEmpty(projects);

        foreach (var (path, project) in projects)
        {
            string relativePath = Path.GetRelativePath(root, path).Replace(Path.DirectorySeparatorChar, '/');
            var isTestProject = Assert.Single(
                project.Descendants(),
                static element => element.Name.LocalName == "IsTestProject");
            var outputType = Assert.Single(
                project.Descendants(),
                static element => element.Name.LocalName == "OutputType");

            Assert.Null(isTestProject.Attribute("Condition"));
            Assert.Equal("true", isTestProject.Value.Trim(), ignoreCase: true);
            Assert.True(
                string.Equals(outputType.Value.Trim(), "Exe", StringComparison.OrdinalIgnoreCase),
                $"{relativePath} must remain an executable xUnit v3 test project.");
        }
    }

    /// <summary>
    /// The gate for the dot-directory prune in <see cref="EnumerateRepositoryProjects"/>
    /// (#3422). Without it, <see cref="OnlyCliProjectsOptIntoToolDefaults"/> fails for any
    /// contributor whose linked worktree lives under the repository root — a failure that
    /// reads as a regression in whatever change is under test, and that CI never sees because
    /// it clones fresh. Hermetic rather than repository-shaped so it holds whether or not the
    /// machine running it happens to have a worktree present.
    /// </summary>
    [Fact]
    public void ProjectScanSkipsDotDirectoriesAndBuildOutput()
    {
        string temp = Path.Combine(Path.GetTempPath(), $"packaging-scan-{Guid.NewGuid():N}");
        try
        {
            string Project(params string[] segments)
            {
                string directory = Path.Combine([temp, .. segments]);
                Directory.CreateDirectory(directory);
                string path = Path.Combine(directory, "sample.csproj");
                File.WriteAllText(path, "<Project />");
                return path;
            }

            string own = Project("src", "tool");
            string obj = Project("src", "tool", "obj");
            string linkedWorktree = Project(".worktrees", "feature", "src", "tool");
            string otherToolState = Project(".claude", "scratch");
            string ordinaryNested = Project("scratch", "copy");

            var found = EnumerateRepositoryProjects(temp).ToArray();

            Assert.Contains(own, found);
            Assert.DoesNotContain(obj, found);
            Assert.DoesNotContain(linkedWorktree, found);
            // Any dot directory is tooling state, not only the repository's own convention.
            Assert.DoesNotContain(otherToolState, found);
            // Negative case: the prune keys on the leading dot, not on depth, so an ordinary
            // nested directory stays censused.
            Assert.Contains(ordinaryNested, found);
        }
        finally
        {
            if (Directory.Exists(temp))
                Directory.Delete(temp, recursive: true);
        }
    }

    static void AssertProperty(XElement group, string name, string expected)
    {
        var property = Assert.Single(group.Elements(), element => element.Name.LocalName == name);
        Assert.Equal(expected, property.Value.Trim(), ignoreCase: true);
    }

    static void AssertShippingPropertyIsOffByDefault(string propertyName)
    {
        string root = FindRepositoryRoot();
        var properties = XDocument
            .Load(Path.Combine(root, "Directory.Build.props"))
            .Descendants()
            .Where(element => element.Name.LocalName == propertyName)
            .ToArray();

        var element = Assert.Single(properties);

        Assert.Null(element.Attribute("Condition"));
        Assert.Equal("false", element.Value.Trim(), ignoreCase: true);
    }

    static (string[] Projects, int Scanned) ScanProjectsForProperty(string propertyName)
    {
        string root = FindRepositoryRoot();
        List<string> matches = [];
        int scanned = 0;

        foreach (string path in EnumerateRepositoryProjects(root))
        {
            scanned++;
            bool optsIn = XDocument.Load(path)
                .Descendants()
                .Any(element => element.Name.LocalName == propertyName
                    && string.Equals(element.Value.Trim(), "true", StringComparison.OrdinalIgnoreCase));

            if (optsIn)
                matches.Add(Path.GetRelativePath(root, path).Replace(Path.DirectorySeparatorChar, '/'));
        }

        matches.Sort(StringComparer.Ordinal);
        return (matches.ToArray(), scanned);
    }

    /// <summary>
    /// Every <c>*.csproj</c> belonging to <em>this</em> checkout. Build output and dot
    /// directories are both excluded, for the same reason: neither holds a project this
    /// repository declares. A dot directory is tooling state — <c>.git</c>, <c>.vs</c>,
    /// <c>.claude</c>, and by the <c>AGENTS.md</c> worktree convention <c>.worktrees</c> —
    /// and never source. Skipping the whole class is what makes the census survive that
    /// worktree workflow (#3422): a linked worktree placed under the root carries its own
    /// copy of <c>src/dotnet-inspect/dotnet-inspect.csproj</c>, which is legitimately
    /// a tool and would be censused as a second tool project. Every project pruned
    /// this way is a duplicate of one the real tree already contributes, so the prune takes
    /// nothing away from the census. The rule is by name, so a nested checkout parked under
    /// an ordinary name is deliberately not covered.
    /// </summary>
    static IEnumerable<string> EnumerateRepositoryProjects(string root)
    {
        var pending = new Stack<string>();
        pending.Push(root);

        while (pending.Count > 0)
        {
            string directory = pending.Pop();

            foreach (string path in Directory.EnumerateFiles(directory, "*.csproj"))
                yield return path;

            foreach (string child in Directory.EnumerateDirectories(directory))
            {
                if (IsExcludedDirectory(child))
                    continue;
                pending.Push(child);
            }
        }
    }

    static bool IsExcludedDirectory(string directory)
    {
        string name = Path.GetFileName(directory);
        return name.StartsWith('.') || name is "bin" or "obj" or "artifacts" or "node_modules";
    }

    static string FindRepositoryRoot()
    {
        for (var directory = new DirectoryInfo(AppContext.BaseDirectory); directory is not null; directory = directory.Parent)
        {
            if (File.Exists(Path.Combine(directory.FullName, "dotnet-inspect.slnx")))
                return directory.FullName;
        }

        throw new DirectoryNotFoundException("Could not find repository root containing dotnet-inspect.slnx.");
    }
}
