<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>$(DefaultTargetFramework)</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>preview</LangVersion>
  </PropertyGroup>

  <PropertyGroup>
    <Authors>Richard Lander</Authors>
    <Description>SourceLink map interpretation, source correlation, and provenance</Description>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="ILInspector.Metadata.Tests" />
    <ProjectReference Include="..\Inspector.Findings\Inspector.Findings.csproj" />
    <ProjectReference Include="..\ILInspector.Metadata\ILInspector.Metadata.csproj" />
    <ProjectReference Include="..\ILInspector.MetadataPrimitives\ILInspector.MetadataPrimitives.csproj" />
  </ItemGroup>

</Project>
