<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>14.0</LangVersion>
  </PropertyGroup>

  <PropertyGroup>
    <Authors>Richard Lander</Authors>
    <Description>Shared services for NuGet package resolution and project asset discovery</Description>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="DotnetInspector.Services.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../DotnetInspector.Packages/DotnetInspector.Packages.csproj" />
  </ItemGroup>

</Project>
