<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>$(DefaultTargetFramework)</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DotnetInspector.Services.RouteLearning.Base\DotnetInspector.Services.RouteLearning.Base.csproj" />
  </ItemGroup>

</Project>
