<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>$(DefaultTargetFramework)</TargetFramework>
    <LangVersion>preview</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <AssemblyName>issue128-experiment</AssemblyName>
    <RootNamespace>ILInspector.Issue128Experiment</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Markout" />
  </ItemGroup>

</Project>
