<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>$(DefaultTargetFramework)</TargetFramework>
    <RootNamespace></RootNamespace>
    <IsPackable>false</IsPackable>
    <IsAotCompatible>false</IsAotCompatible>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <LangVersion>latest</LangVersion>
    <EnablePreviewFeatures>false</EnablePreviewFeatures>
  </PropertyGroup>

</Project>
