<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>$(DefaultTargetFramework)</TargetFramework>
    <LangVersion>preview</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <IsAotCompatible>false</IsAotCompatible>
    <OutputType>Exe</OutputType>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
    <Using Include="ILInspector.SourceLink" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DiffFixtures.V1\DiffFixtures.V1.csproj" ReferenceOutputAssembly="false" />
    <ProjectReference Include="..\DiffFixtures.V2\DiffFixtures.V2.csproj" ReferenceOutputAssembly="false" />
    <ProjectReference Include="..\ILInspector.Decompiler\ILInspector.Decompiler.csproj" />
    <ProjectReference Include="..\ILInspector.Metadata\ILInspector.Metadata.csproj" />
    <ProjectReference Include="..\ILInspector.Research\ILInspector.Research.csproj" />
    <ProjectReference Include="..\ILInspector.SourceLink\ILInspector.SourceLink.csproj" />
    <ProjectReference Include="..\..\tests\DotnetInspector.Fixtures\DotnetInspector.Fixtures.csproj" />
  </ItemGroup>

</Project>
