<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>$(DefaultTargetFramework)</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>preview</LangVersion>
  </PropertyGroup>

  <PropertyGroup>
    <Authors>Richard Lander</Authors>
    <Description>Static application catalog for .NET ecosystem package sets and integrations</Description>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DotnetInspector.Packages\DotnetInspector.Packages.csproj" />
    <InternalsVisibleTo Include="DotnetInspector.Ecosystems.Tests" />
  </ItemGroup>

</Project>
