#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

ENV_FILE="$REPO_ROOT/.env.build-events"
TOOLS_BIN="$REPO_ROOT/.build-event-tools/bin"

VMR_ROOT_DEFAULT="/home/rich/git/dotnet-build-events-vmr-e2e"
BAD_CODE_ROOT_DEFAULT="/home/rich/git/bad-code"
HOST_DOTNET_DEFAULT="${DOTNET:-$(command -v dotnet)}"

VMR_ROOT="${BUILD_EVENT_VMR_ROOT:-$VMR_ROOT_DEFAULT}"
VMR_DOTNET="${BUILD_EVENT_VMR_DOTNET:-$VMR_ROOT/src/sdk/artifacts/bin/redist/Debug/dotnet/dotnet}"
BAD_CODE_ROOT="${BUILD_EVENT_BAD_CODE_ROOT:-$BAD_CODE_ROOT_DEFAULT}"
RUN_DIR="${BUILD_EVENT_RUN_DIR:-$REPO_ROOT/artifacts/build-event-runs}"
AUTO_EVENT_LOG_DIR="${BUILD_EVENT_AUTO_EVENT_LOG_DIR:-$RUN_DIR/direct}"
ALWAYS_EVENT_LOG="${BUILD_EVENT_ALWAYS_EVENT_LOG:-1}"
AUTO_EVENT_LOG_STDERR="${BUILD_EVENT_AUTO_EVENT_LOG_STDERR:-1}"
HOST_DOTNET="${BUILD_EVENT_HOST_DOTNET:-$HOST_DOTNET_DEFAULT}"
DOTNET_INSPECT_PROJECT="$REPO_ROOT/src/dotnet-inspect"

if [[ ! -x "$VMR_DOTNET" ]]; then
    echo "error: VMR dotnet not found or not executable: $VMR_DOTNET" >&2
    echo "set BUILD_EVENT_VMR_ROOT or BUILD_EVENT_VMR_DOTNET before running this script" >&2
    exit 1
fi

if [[ ! -d "$BAD_CODE_ROOT" ]]; then
    echo "warning: bad-code repo not found: $BAD_CODE_ROOT" >&2
fi

mkdir -p "$TOOLS_BIN" "$RUN_DIR"
mkdir -p "$AUTO_EVENT_LOG_DIR"

cat > "$ENV_FILE" <<EOF
# Generated by scripts/setup-build-event-env.sh.
BUILD_EVENT_REPO_ROOT="$REPO_ROOT"
BUILD_EVENT_VMR_ROOT="$VMR_ROOT"
BUILD_EVENT_VMR_DOTNET="$VMR_DOTNET"
BUILD_EVENT_BAD_CODE_ROOT="$BAD_CODE_ROOT"
BUILD_EVENT_RUN_DIR="$RUN_DIR"
BUILD_EVENT_TOOLS_BIN="$TOOLS_BIN"
BUILD_EVENT_ALWAYS_EVENT_LOG="$ALWAYS_EVENT_LOG"
BUILD_EVENT_AUTO_EVENT_LOG_DIR="$AUTO_EVENT_LOG_DIR"
BUILD_EVENT_AUTO_EVENT_LOG_STDERR="$AUTO_EVENT_LOG_STDERR"
BUILD_EVENT_HOST_DOTNET="$HOST_DOTNET"
BUILD_EVENT_DOTNET_INSPECT_PROJECT="$DOTNET_INSPECT_PROJECT"
EOF

ln -sfn "$VMR_DOTNET" "$TOOLS_BIN/dotnet-vmr"

cat > "$TOOLS_BIN/dotnet" <<'EOF'
#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
# shellcheck disable=SC1091
source "$REPO_ROOT/.env.build-events"

json_escape() {
    local value="$1"
    value="${value//\\/\\\\}"
    value="${value//\"/\\\"}"
    value="${value//$'\n'/\\n}"
    value="${value//$'\r'/\\r}"
    printf '%s' "$value"
}

write_json_array() {
    local first=1
    printf '['
    for value in "$@"; do
        if [[ $first -eq 0 ]]; then
            printf ','
        fi
        first=0
        printf '"%s"' "$(json_escape "$value")"
    done
    printf ']'
}

has_arg() {
    local needle="$1"
    shift
    for value in "$@"; do
        if [[ "$value" == "$needle" || "$value" == "$needle="* ]]; then
            return 0
        fi
    done
    return 1
}

is_build=false
if [[ "${1:-}" == "build" ]]; then
    is_build=true
fi

if [[ "$is_build" == true && "${BUILD_EVENT_ALWAYS_EVENT_LOG:-1}" == "1" ]] &&
    ! has_arg "--event-log" "$@" &&
    ! has_arg "--event-log-file" "$@" &&
    ! has_arg "--event-log-dir" "$@" &&
    ! has_arg "--no-event-log" "$@"; then
    mkdir -p "$BUILD_EVENT_AUTO_EVENT_LOG_DIR"
    stamp="$(date -u +%Y%m%dT%H%M%SZ)"
    run_dir="$BUILD_EVENT_AUTO_EVENT_LOG_DIR/$stamp-$$"
    mkdir -p "$run_dir"
    log_file="$run_dir/build.jsonl"
    manifest_file="$run_dir/manifest.json"
    args=("$@" --event-log-file "$log_file")
    if [[ "${BUILD_EVENT_AUTO_EVENT_LOG_STDERR:-1}" == "1" ]]; then
        args+=(--event-log-stderr)
    fi
    set +e
    "$BUILD_EVENT_VMR_DOTNET" "${args[@]}"
    exit_code=$?
    set -e
    dotnet_version="$("$BUILD_EVENT_VMR_DOTNET" --version)"
    {
        printf '{\n'
        printf '  "schemaVersion": 1,\n'
        printf '  "capturedAt": "%s",\n' "$(json_escape "$stamp")"
        printf '  "command": '
        write_json_array "$BUILD_EVENT_VMR_DOTNET" "${args[@]}"
        printf ',\n'
        printf '  "dotnetVersion": "%s",\n' "$(json_escape "$dotnet_version")"
        printf '  "eventLog": "%s",\n' "$(json_escape "$log_file")"
        printf '  "exitCode": %s,\n' "$exit_code"
        printf '  "workingDirectory": "%s"\n' "$(json_escape "$(pwd)")"
        printf '}\n'
    } > "$manifest_file"
    exit "$exit_code"
fi

exec "$BUILD_EVENT_VMR_DOTNET" "$@"
EOF

cat > "$TOOLS_BIN/dotnet-build-events" <<'EOF'
#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
exec "$SCRIPT_DIR/dotnet" "$@"
EOF

cat > "$TOOLS_BIN/dotnet-inspect-dev" <<'EOF'
#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
# shellcheck disable=SC1091
source "$REPO_ROOT/.env.build-events"

exec "$BUILD_EVENT_HOST_DOTNET" run --project "$BUILD_EVENT_DOTNET_INSPECT_PROJECT" -c Release --no-build -- "$@"
EOF

cat > "$TOOLS_BIN/capture-build-event-log" <<'EOF'
#!/usr/bin/env bash
set -euo pipefail

if [[ $# -lt 1 ]]; then
    echo "usage: capture-build-event-log <project-or-sln> [name] [extra dotnet build args...]" >&2
    exit 2
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
# shellcheck disable=SC1091
source "$REPO_ROOT/.env.build-events"

PROJECT="$1"
shift
NAME="${1:-$(basename "${PROJECT%.*}")}"
if [[ $# -gt 0 ]]; then
    shift
fi

STAMP="$(date -u +%Y%m%dT%H%M%SZ)"
OUT_DIR="$BUILD_EVENT_RUN_DIR/$STAMP-$NAME"
LOG_FILE="$OUT_DIR/$NAME.jsonl"
STDOUT_FILE="$OUT_DIR/stdout.txt"
STDERR_FILE="$OUT_DIR/stderr.txt"
EXIT_FILE="$OUT_DIR/exit-code.txt"
MANIFEST_FILE="$OUT_DIR/manifest.json"
mkdir -p "$OUT_DIR"

BUILD_ARGS=(build --no-restore --view summary --event-log-file "$LOG_FILE" "$PROJECT" "$@")

set +e
"$BUILD_EVENT_VMR_DOTNET" "${BUILD_ARGS[@]}" >"$STDOUT_FILE" 2>"$STDERR_FILE"
EXIT_CODE=$?
set -e

printf '%s\n' "$EXIT_CODE" > "$EXIT_FILE"

json_escape() {
    local value="$1"
    value="${value//\\/\\\\}"
    value="${value//\"/\\\"}"
    value="${value//$'\n'/\\n}"
    value="${value//$'\r'/\\r}"
    printf '%s' "$value"
}

write_json_array() {
    local first=1
    printf '['
    for value in "$@"; do
        if [[ $first -eq 0 ]]; then
            printf ','
        fi
        first=0
        printf '"%s"' "$(json_escape "$value")"
    done
    printf ']'
}

PROJECT_DIR="$(cd "$(dirname "$PROJECT")" && pwd)"
if git -C "$PROJECT_DIR" rev-parse --show-toplevel >/dev/null 2>&1; then
    GIT_ROOT="$(git -C "$PROJECT_DIR" rev-parse --show-toplevel)"
    GIT_HEAD="$(git -C "$PROJECT_DIR" rev-parse HEAD)"
    GIT_BRANCH="$(git -C "$PROJECT_DIR" branch --show-current)"
    if [[ -n "$(git -C "$PROJECT_DIR" status --porcelain)" ]]; then
        GIT_DIRTY=true
    else
        GIT_DIRTY=false
    fi
else
    GIT_ROOT=""
    GIT_HEAD=""
    GIT_BRANCH=""
    GIT_DIRTY=false
fi

DOTNET_VERSION="$("$BUILD_EVENT_VMR_DOTNET" --version)"

{
    printf '{\n'
    printf '  "schemaVersion": 1,\n'
    printf '  "capturedAt": "%s",\n' "$(json_escape "$STAMP")"
    printf '  "name": "%s",\n' "$(json_escape "$NAME")"
    printf '  "project": "%s",\n' "$(json_escape "$PROJECT")"
    printf '  "workingDirectory": "%s",\n' "$(json_escape "$(pwd)")"
    printf '  "command": '
    write_json_array "$BUILD_EVENT_VMR_DOTNET" "${BUILD_ARGS[@]}"
    printf ',\n'
    printf '  "dotnetVersion": "%s",\n' "$(json_escape "$DOTNET_VERSION")"
    printf '  "eventLog": "%s",\n' "$(json_escape "$LOG_FILE")"
    printf '  "stdout": "%s",\n' "$(json_escape "$STDOUT_FILE")"
    printf '  "stderr": "%s",\n' "$(json_escape "$STDERR_FILE")"
    printf '  "exitCode": %s,\n' "$EXIT_CODE"
    printf '  "git": {\n'
    printf '    "root": "%s",\n' "$(json_escape "$GIT_ROOT")"
    printf '    "head": "%s",\n' "$(json_escape "$GIT_HEAD")"
    printf '    "branch": "%s",\n' "$(json_escape "$GIT_BRANCH")"
    printf '    "dirty": %s\n' "$GIT_DIRTY"
    printf '  }\n'
    printf '}\n'
} > "$MANIFEST_FILE"

printf 'event_log=%s\nstdout=%s\nstderr=%s\nmanifest=%s\nexit_code=%s\n' "$LOG_FILE" "$STDOUT_FILE" "$STDERR_FILE" "$MANIFEST_FILE" "$EXIT_CODE"
exit "$EXIT_CODE"
EOF

chmod +x "$TOOLS_BIN/dotnet" "$TOOLS_BIN/dotnet-build-events" "$TOOLS_BIN/dotnet-inspect-dev" "$TOOLS_BIN/capture-build-event-log"

echo "Building local dotnet-inspect..."
"$HOST_DOTNET" build "$DOTNET_INSPECT_PROJECT" -c Release --nologo

echo
echo "Build-event environment ready."
echo "To use in this shell:"
echo "  source $ENV_FILE"
echo "  export PATH=\"\$BUILD_EVENT_TOOLS_BIN:\$PATH\""
echo
echo "Commands:"
echo "  dotnet --version"
echo "  dotnet-build-events --version"
echo "  dotnet-inspect-dev build samples/build-event-logs/zerodaysearch.jsonl -S Summary --tsv"
echo "  capture-build-event-log \"\$BUILD_EVENT_BAD_CODE_ROOT/ZeroDaySearch/ZeroDaySearch.csproj\" zerodaysearch"
