<Project Sdk="Microsoft.NET.Sdk.WebAssembly">

  <PropertyGroup>
    <TargetFramework>$(DefaultTargetFramework)</TargetFramework>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <EnablePreviewFeatures>true</EnablePreviewFeatures>
    <OverrideHtmlAssetPlaceholders>true</OverrideHtmlAssetPlaceholders>
    <IsPublishable>true</IsPublishable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/ILInspector.MetadataPrimitives/ILInspector.MetadataPrimitives.csproj" />
  </ItemGroup>

  <ItemGroup>
    <StaticWebAssetFingerprintPattern
      Include="JS"
      Pattern="*.js"
      Expression="#[.{fingerprint}]!" />
  </ItemGroup>

</Project>
