<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>$(DefaultTargetFramework)</TargetFramework>
    <LangVersion>preview</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <IsPackable>false</IsPackable>
    <IsPublishable>false</IsPublishable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" />
    <ProjectReference Include="../../src/CSharpText/CSharpText.csproj" />
    <ProjectReference Include="../../src/DotnetInspector.SourceHouse/DotnetInspector.SourceHouse.csproj" />
    <ProjectReference Include="../../src/ILInspector.Metadata/ILInspector.Metadata.csproj" />
  </ItemGroup>

</Project>
