<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>$(DefaultTargetFramework)</TargetFramework>
    <LangVersion>preview</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <IsPackable>false</IsPackable>
    <AssemblyName>il-diff-harness</AssemblyName>
    <RootNamespace>ILInspector.IlDiffHarness</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../DiffHarnessCommon/DiffHarnessCommon.csproj" />
    <ProjectReference Include="../../src/ILInspector.Instructions/ILInspector.Instructions.csproj" />
    <PackageReference Include="Markout" />
  </ItemGroup>

</Project>
