// GENERATED FILE — DO NOT EDIT BY HAND.
//
// Generated by tsbindgen from InspectWeb.Engine.dll's [JSExport] surface. Regenerate with:
//   eng/generate-inspect-web-engine-dts.sh
// CI fails if the committed file drifts from this output.

export type BrowserDependencyCoordinateMatchOutcome = "NoMatch" | "Unique" | "Ambiguous";

export type BrowserDependencyCoordinateProvenance = "NuGetPackage" | "PlatformRuntime";

export interface BrowserAccessibilityDescriptor {
  id: string;
  label: string;
  order: number;
  isDefault: boolean;
  count: number;
}

export interface BrowserAnnotatedSource {
  document: unknown;
  provenance: string;
  contextLimitation: string | null;
}

export interface BrowserAssemblyReference {
  name: string;
  version: string;
  culture: string | null;
  publicKeyToken: string | null;
}

export interface BrowserAssemblySurface {
  id: string;
  name: string;
  version: string;
  culture: string | null;
  publicKeyToken: string | null;
  asset: string;
  publicTypes: number;
  publicMembers: number;
}

export interface BrowserBuildIdentity {
  version: string;
  commit: string | null;
  builtAtUtc: string | null;
  commitUrl: string | null;
}

export interface BrowserCallGraph {
  mermaid: string;
  callers: BrowserCallGraphNode;
  callees: BrowserCallGraphNode;
  scope: BrowserCallGraphScope;
  targets: BrowserCallGraphTarget[];
  diagnostics: BrowserCallGraphDiagnostics;
  noBody: boolean;
}

export interface BrowserCallGraphDiagnostics {
  incompleteNodes: number;
  incompleteEdges: number;
  bindingIdentityConflicts: number;
  hasUnexploredTraversalBoundary: boolean;
  hasAnalysisFailureBoundary: boolean;
  isIncomplete: boolean;
}

export interface BrowserCallGraphNode {
  label: string;
  status: string;
  inLoop: boolean;
  source: string | null;
  children: BrowserCallGraphNode[];
  assembly: string;
  typeFullName: string;
  memberName: string;
}

export interface BrowserCallGraphScope {
  packages: number;
  assemblies: number;
  callerAssemblies: number;
  calleeScope: string;
}

export interface BrowserCallGraphTarget {
  id: string;
  assembly: string;
  assemblyVersion: string | null;
  assemblyCulture: string | null;
  assemblyPublicKeyToken: string | null;
  typeFullName: string;
  typeMetadataId: string | null;
  typeDefinitionId: string | null;
  memberName: string;
  parameterTypes: string[];
  returnType: string;
  genericArity: number;
  metadataToken: number | null;
  selectorKey: string;
  kind: string;
}

export interface BrowserDependencyCoordinateCandidate {
  key: string;
  provenance: BrowserDependencyCoordinateProvenance;
  packageId: string;
  version: string;
  targetFramework: string;
}

export interface BrowserDependencyCoordinateMatch {
  outcome: BrowserDependencyCoordinateMatchOutcome;
  candidateKey: string | null;
}

export interface BrowserExceptionSurface {
  type: string;
  description: string;
}

export interface BrowserIntegrationCategory {
  integration: string;
  signals: BrowserIntegrationSignal[];
}

export interface BrowserIntegrationSignal {
  kind: string;
  name: string;
  shape: string;
}

export interface BrowserMemberBodySelector {
  token: number;
  memberName: string;
  selectorKey: string;
}

export interface BrowserMemberDocumentation {
  summary: string | null;
  returns: string | null;
  parameters: Record<string, string>;
  exceptions: BrowserExceptionSurface[];
}

export interface BrowserMemberSurface {
  name: string;
  kind: string;
  signature: string;
  accessibility: string;
  isStatic: boolean;
  isUnsafe: boolean;
  isVirtual: boolean;
  isAbstract: boolean;
  isOverride: boolean;
  isExtension: boolean;
  isObsolete: boolean;
  genericArity: number;
  metadataToken: number | null;
  returnType: string | null;
  parameters: BrowserParameterSurface[];
  documentationId: string | null;
  summary: string | null;
  returns: string | null;
  exceptions: BrowserExceptionSurface[];
  stableSelector: string;
  anchorDigest: string;
  canonicalSignature: string;
  graphSelectorKey: string;
  bodySelectors: BrowserMemberBodySelector[];
}

export interface BrowserOpportunityCategory {
  integration: string;
  items: BrowserOpportunityItem[];
}

export interface BrowserOpportunityItem {
  api: string;
  integrationType: string;
  lookFor: string;
}

export interface BrowserPackageCacheStats {
  packages: number;
  resident: number;
  workspaces: number;
  residentBytes: number;
}

export interface BrowserPackageDependencies {
  package: string;
  version: string;
  activeFramework: string;
  assembly: string;
  dependencyGroups: BrowserPackageDependencyGroup[];
  assemblyReferences: BrowserAssemblyReference[];
  dependencyGroupError: string | null;
  assemblyReferenceError: string | null;
}

export interface BrowserPackageDependency {
  id: string;
  versionRange: string;
}

export interface BrowserPackageDependencyGroup {
  index: number;
  framework: string;
  isActive: boolean;
  dependencies: BrowserPackageDependency[];
}

export interface BrowserPackageDocument {
  kind: string;
  name: string;
  path: string;
  size: number;
}

export interface BrowserPackageDocumentContent {
  kind: string;
  name: string;
  path: string;
  text: string;
}

export interface BrowserPackageIntegrations {
  package: string;
  version: string;
  framework: string;
  categories: BrowserIntegrationCategory[];
  totalSignals: number;
  isComplete: boolean;
  inspectionError: string | null;
}

export interface BrowserPackageOpportunities {
  package: string;
  version: string;
  activeFramework: string;
  categories: BrowserOpportunityCategory[];
  totalOpportunities: number;
  isComplete: boolean;
  inspectionError: string | null;
}

export interface BrowserPackageSurface {
  package: string;
  version: string;
  frameworks: string[];
  activeFramework: string;
  defaultAssemblyId: string;
  assemblies: BrowserAssemblySurface[];
  types: BrowserTypeSurface[];
  accessibility: BrowserAccessibilityDescriptor[];
  totalMembers: number;
  documents: BrowserPackageDocument[];
  inspectionError: string | null;
}

export interface BrowserParameterSurface {
  name: string;
  type: string;
  modifier: string | null;
  hasDefault: boolean;
  defaultValue: string | null;
  description: string | null;
}

export interface BrowserSource {
  provider: string;
  provenance: string;
  url: string | null;
  text: string;
}

export interface BrowserTypeCandidate {
  key: string;
  name: string;
  full: string;
}

export interface BrowserTypeComposition {
  methods: number;
  properties: number;
  fields: number;
  events: number;
  constructors: number;
  operators: number;
  explicitInterfaceImplementations: number;
  extensionMethods: number;
  static: number;
  unsafe: number;
  async: number;
  virtual: number;
  abstract: number;
  override: number;
  extension: number;
  obsolete: number;
  total: number;
}

export interface BrowserTypeGraphEdge {
  fromId: string;
  toId: string;
  kind: string;
}

export interface BrowserTypeGraphNode {
  id: string;
  displayName: string;
  role: string;
}

export interface BrowserTypeMetadata {
  fullName: string;
  namespace: string | null;
  name: string;
  kind: string;
  modifiers: string[];
  accessibility: string | null;
  assembly: string | null;
  baseType: string | null;
  interfaces: string[];
  derivedTypes: string[];
  typeParameters: BrowserTypeParameter[];
  attributes: string[];
  enumUnderlyingType: string | null;
  composition: BrowserTypeComposition | null;
  graphNodes: BrowserTypeGraphNode[];
  graphEdges: BrowserTypeGraphEdge[];
  inspectionFailures: string[];
}

export interface BrowserTypeParameter {
  name: string;
  variance: string | null;
  constraints: string[];
}

export interface BrowserTypeSearchHit {
  key: string;
  kind: string;
}

export interface BrowserTypeSurface {
  id: string;
  definitionId: string;
  queryId: string;
  metadataId: string;
  name: string;
  displayName: string;
  namespace: string;
  kind: string;
  accessibility: string;
  accessibilityId: string;
  assembly: string;
  assemblyId: string;
  assemblyName: string;
  members: number;
  signature: string;
  api: BrowserMemberSurface[];
}

export interface BrowserVocabularyDocument {
  schemaVersion: number;
  sections: BrowserVocabularySection[];
}

export interface BrowserVocabularyField {
  id: string;
  label: string;
  summary: string;
  type: string;
  operators: string[];
}

export interface BrowserVocabularySection {
  id: string;
  name: string;
  summary: string;
  categories: string[];
  acceptedBy: string[];
  fields: BrowserVocabularyField[];
  values: unknown[];
}

export interface BrowserWorkspacePackage {
  package: string;
  version: string;
  framework: string;
}

export declare function BuildIdentity(): BrowserBuildIdentity;
export declare function CancelSourceQuery(): void;
export declare function ConfigureHost(origin: string): void;
export declare function ExpandPlatformCallGraph(targetFramework: string, assembly: string, typeFullName: string, memberName: string, selectorKey: string, metadataToken: number): Promise<string>;
export declare function GetPackageDocument(packageId: string, version: string, path: string): Promise<BrowserPackageDocumentContent>;
export declare function ListVocabulary(): BrowserVocabularyDocument;
export declare function LoadRuntimePack(targetFramework: string): Promise<string>;
export declare function LoadRuntimePackAssembly(targetFramework: string, assemblyFileName: string, pack: string): Promise<string>;
export declare function MatchPackageDependencyCoordinate(packageId: string, declaredRange: string | null, candidatesJson: string): BrowserDependencyCoordinateMatch;
export declare function PackageCacheStats(): BrowserPackageCacheStats;
export declare function QueryMemberAnnotatedSource(packageId: string, version: string, targetFramework: string, assemblyName: string, typeIdentity: string, typeQueryId: string, memberName: string, memberSignature: string, selectorKey: string, metadataToken: number, styleOptionsJson: string): Promise<string>;
export declare function QueryMemberCallGraph(packageId: string, version: string, targetFramework: string, assemblyName: string, typeIdentity: string, typeQueryId: string, memberName: string, memberSignature: string, selectorKey: string, metadataToken: number, workspaceJson: string): Promise<BrowserCallGraph>;
export declare function QueryMemberDocumentation(packageId: string, version: string, framework: string, assemblyName: string, documentationId: string): Promise<BrowserMemberDocumentation>;
export declare function QueryMemberFacts(packageId: string, version: string, targetFramework: string, assemblyName: string, typeId: string, memberName: string, memberSignature: string): Promise<string>;
export declare function QueryMemberSource(packageId: string, version: string, targetFramework: string, assemblyName: string, typeIdentity: string, memberName: string, selectorKey: string, metadataToken: number, styleOptionsJson: string): Promise<string>;
export declare function QueryPackage(packageId: string, version: string, targetFramework: string): Promise<BrowserPackageSurface>;
export declare function QueryPackageDependencies(packageId: string, version: string, targetFramework: string, assemblyId: string): Promise<BrowserPackageDependencies>;
export declare function QueryPackageHeapEntries(packageId: string, version: string, targetFramework: string, assemblyFileName: string, heap: string): Promise<string>;
export declare function QueryPackageIntegrations(packageId: string, version: string, targetFramework: string): Promise<BrowserPackageIntegrations>;
export declare function QueryPackageMetadata(packageId: string, version: string, targetFramework: string): Promise<string>;
export declare function QueryPackageMetadataTable(packageId: string, version: string, targetFramework: string, assemblyFileName: string, tableIndex: number, startRowId: number, maxRows: number): Promise<string>;
export declare function QueryPackageOpportunities(packageId: string, version: string, targetFramework: string): Promise<BrowserPackageOpportunities>;
export declare function QueryPackagePerformance(packageId: string, version: string, targetFramework: string): Promise<string>;
export declare function QueryPackageVersions(packageId: string): Promise<string[]>;
export declare function QueryPlatformHeapEntries(targetFramework: string, assemblyFileName: string, pack: string, heap: string): Promise<string>;
export declare function QueryPlatformIntegrations(targetFramework: string, assemblyFileName: string, pack: string): Promise<string>;
export declare function QueryPlatformMetadata(targetFramework: string, assemblyFileName: string, pack: string): Promise<string>;
export declare function QueryPlatformMetadataTable(targetFramework: string, assemblyFileName: string, pack: string, tableIndex: number, startRowId: number, maxRows: number): Promise<string>;
export declare function QueryPlatformOpportunities(targetFramework: string, assemblyFileName: string, pack: string): Promise<string>;
export declare function QueryPlatformPerformance(targetFramework: string, assemblyFileName: string, pack: string): Promise<string>;
export declare function QueryTypeMemberSource(packageId: string, version: string, targetFramework: string, assemblyName: string, typeIdentity: string, memberName: string, selectorKey: string, metadataToken: number, styleOptionsJson: string): Promise<string>;
export declare function QueryTypeProjection(packageId: string, version: string, targetFramework: string, assemblyName: string, typeId: string): Promise<BrowserTypeMetadata>;
export declare function QueryTypeSource(packageId: string, version: string, targetFramework: string, assemblyName: string, typeIdentity: string, styleOptionsJson: string): Promise<BrowserSource>;
export declare function ResolvePackageDependencyVersion(packageId: string, declaredRange: string | null): Promise<string>;
export declare function SearchTypes(query: string, candidatesJson: string): BrowserTypeSearchHit[];
