// GENERATED FILE — DO NOT EDIT BY HAND.
//
// Generated by tsbindgen from InspectWeb.Engine.dll's [JSExport] surface. Regenerate with:
//   eng/generate-inspect-web-engine-dts.sh
// CI fails if the committed file drifts from this output.

export type BrowserDependencyCoordinateMatchOutcome = "NoMatch" | "Unique" | "Ambiguous";

export type BrowserDependencyCoordinateProvenance = "NuGetPackage" | "PlatformRuntime";

export interface BrowserAccessibilityDescriptor {
  id: string;
  label: string;
  order: number;
  isDefault: boolean;
  count: number;
}

export interface BrowserAnnotatedSource {
  document: unknown;
  provenance: string;
  contextLimitation: string | null;
}

export interface BrowserAssemblyMetadata {
  assembly: string;
  metadataVersion: string;
  kind: string;
  isAssembly: boolean;
  metadataSize: number;
  projectedTableTotal: number;
  heaps: BrowserMetadataHeap[];
  tables: BrowserMetadataTable[];
  headers: BrowserMetadataHeaders;
}

export interface BrowserAssemblyReference {
  name: string;
  version: string;
  culture: string | null;
  publicKeyToken: string | null;
}

export interface BrowserAssemblySurface {
  id: string;
  name: string;
  version: string;
  culture: string | null;
  publicKeyToken: string | null;
  asset: string;
  publicTypes: number;
  publicMembers: number;
  platformPack: string | null;
}

export interface BrowserBuildIdentity {
  version: string;
  commit: string | null;
  builtAtUtc: string | null;
  commitUrl: string | null;
}

export interface BrowserCallGraph {
  mermaid: string;
  callers: BrowserCallGraphNode;
  callees: BrowserCallGraphNode;
  scope: BrowserCallGraphScope;
  targets: BrowserCallGraphTarget[];
  diagnostics: BrowserCallGraphDiagnostics;
  noBody: boolean;
}

export interface BrowserCallGraphDiagnostics {
  incompleteNodes: number;
  incompleteEdges: number;
  bindingIdentityConflicts: number;
  hasUnexploredTraversalBoundary: boolean;
  hasAnalysisFailureBoundary: boolean;
  isIncomplete: boolean;
}

export interface BrowserCallGraphNode {
  label: string;
  status: string;
  inLoop: boolean;
  source: string | null;
  children: BrowserCallGraphNode[];
  assembly: string;
  typeFullName: string;
  memberName: string;
}

export interface BrowserCallGraphScope {
  packages: number;
  assemblies: number;
  callerAssemblies: number;
  calleeScope: string;
}

export interface BrowserCallGraphTarget {
  id: string;
  assembly: string;
  assemblyVersion: string | null;
  assemblyCulture: string | null;
  assemblyPublicKeyToken: string | null;
  typeFullName: string;
  typeMetadataId: string | null;
  typeDefinitionId: string | null;
  memberName: string;
  parameterTypes: string[];
  returnType: string;
  genericArity: number;
  metadataToken: number | null;
  selectorKey: string;
  kind: string;
  platformPack: string | null;
}

export interface BrowserDependencyCoordinateCandidate {
  key: string;
  provenance: BrowserDependencyCoordinateProvenance;
  packageId: string;
  version: string;
  targetFramework: string;
}

export interface BrowserDependencyCoordinateMatch {
  outcome: BrowserDependencyCoordinateMatchOutcome;
  candidateKey: string | null;
}

export interface BrowserExceptionSurface {
  type: string;
  description: string;
}

export interface BrowserHeapEntry {
  offset: number;
  value: BrowserMetadataCell;
  referenceCount: number;
}

export interface BrowserHeapListing {
  assembly: string;
  heap: string;
  streamName: string;
  coverage: string;
  entries: BrowserHeapEntry[];
  rowsTruncated: boolean;
  entriesTruncated: boolean;
  error: string | null;
}

export interface BrowserHomeDemoCatalog {
  demos: BrowserHomeDemoCatalogEntry[];
}

export interface BrowserHomeDemoCatalogEntry {
  id: string;
  title: string;
  summary: string;
}

export interface BrowserHomeDemoMember {
  kind: string;
  id: string;
  version: string | null;
  framework: string | null;
  assembly: string | null;
}

export interface BrowserHomeDemoNavigationTab {
  id: string;
  member: BrowserHomeDemoMember;
}

export interface BrowserHomeDemoResolveResult {
  found: boolean;
  demo: BrowserHomeDemoResolved | null;
}

export interface BrowserHomeDemoResolved {
  id: string;
  title: string;
  summary: string;
  workspaceMembers: BrowserHomeDemoMember[];
  tabs: BrowserHomeDemoNavigationTab[];
  focusTabIndex: number;
  view: BrowserHomeDemoView;
}

export interface BrowserHomeDemoRunActivation {
  focusPackage: string;
  focusVersion: string;
  focusFramework: string;
  typeId: string;
  memberName: string;
  memberKind: string;
  memberAnchorDigest: string;
  memberSection: string;
}

export interface BrowserHomeDemoRunResult {
  found: boolean;
  packages: BrowserPackageSurface[];
  activation: BrowserHomeDemoRunActivation | null;
  callGraph: BrowserCallGraph | null;
}

export interface BrowserHomeDemoView {
  library: string | null;
  type: string | null;
  memberAnchor: string | null;
  memberKey: string | null;
  section: string | null;
}

export interface BrowserIntegrationCategory {
  integration: string;
  signals: BrowserIntegrationSignal[];
}

export interface BrowserIntegrationSignal {
  kind: string;
  name: string;
  shape: string;
}

export interface BrowserMemberBodySelector {
  token: number;
  memberName: string;
  selectorKey: string;
}

export interface BrowserMemberDocumentation {
  summary: string | null;
  returns: string | null;
  parameters: Record<string, string>;
  exceptions: BrowserExceptionSurface[];
}

export interface BrowserMemberSurface {
  name: string;
  kind: string;
  signature: string;
  accessibility: string;
  isStatic: boolean;
  isUnsafe: boolean;
  isVirtual: boolean;
  isAbstract: boolean;
  isOverride: boolean;
  isExtension: boolean;
  isObsolete: boolean;
  genericArity: number;
  metadataToken: number | null;
  returnType: string | null;
  parameters: BrowserParameterSurface[];
  documentationId: string | null;
  summary: string | null;
  returns: string | null;
  exceptions: BrowserExceptionSurface[];
  stableSelector: string;
  anchorDigest: string;
  canonicalSignature: string;
  graphSelectorKey: string;
  bodySelectors: BrowserMemberBodySelector[];
}

export interface BrowserMetadataCell {
  kind: string;
  raw: number | null;
  display: string | null;
  decoded: string | null;
  heap: string | null;
  text: string | null;
  preview: string | null;
  offset: number | null;
  length: number | null;
  truncated: boolean | null;
  targetTable: number | null;
  targetRowId: number | null;
  startRowId: number | null;
  endRowId: number | null;
  count: number | null;
  token: number | null;
  detail: string | null;
}

export interface BrowserMetadataColumn {
  name: string;
  kind: string;
  candidateTargets: number[];
}

export interface BrowserMetadataHeaders {
  machine: string;
  isPE32Plus: boolean;
  subsystem: string;
  corFlags: string | null;
  majorRuntimeVersion: number | null;
  minorRuntimeVersion: number | null;
  entryPointToken: number | null;
}

export interface BrowserMetadataHeap {
  name: string;
  sizeInBytes: number;
  maxAddress: number;
  addressing: string;
}

export interface BrowserMetadataRow {
  rowId: number;
  token: number;
  cells: BrowserMetadataCell[];
}

export interface BrowserMetadataTable {
  index: number;
  name: string;
  rowCount: number;
  isProjected: boolean;
}

export interface BrowserMetadataWindow {
  assembly: string;
  index: number;
  name: string;
  rowCount: number;
  startRowId: number;
  columns: BrowserMetadataColumn[];
  rows: BrowserMetadataRow[];
  truncated: boolean;
  error: string | null;
}

export interface BrowserOpportunityCategory {
  integration: string;
  items: BrowserOpportunityItem[];
}

export interface BrowserOpportunityItem {
  api: string;
  integrationType: string;
  lookFor: string;
  sourceDefinitionId: string | null;
  sourceAssembly: string;
  sourceAssemblyVersion: string;
  sourceAssemblyCulture: string | null;
  sourceAssemblyPublicKeyToken: string | null;
}

export interface BrowserPackageCacheStats {
  packages: number;
  resident: number;
  workspaces: number;
  residentBytes: number;
}

export interface BrowserPackageDependencies {
  package: string;
  version: string;
  activeFramework: string;
  assembly: string;
  dependencyGroups: BrowserPackageDependencyGroup[];
  assemblyReferences: BrowserAssemblyReference[];
  dependencyGroupError: string | null;
  assemblyReferenceError: string | null;
}

export interface BrowserPackageDependency {
  id: string;
  versionRange: string;
}

export interface BrowserPackageDependencyGroup {
  index: number;
  framework: string;
  isActive: boolean;
  dependencies: BrowserPackageDependency[];
}

export interface BrowserPackageDocument {
  kind: string;
  name: string;
  path: string;
  size: number;
}

export interface BrowserPackageDocumentContent {
  kind: string;
  name: string;
  path: string;
  text: string;
}

export interface BrowserPackageIntegrations {
  package: string;
  version: string;
  framework: string;
  categories: BrowserIntegrationCategory[];
  totalSignals: number;
  isComplete: boolean;
  inspectionError: string | null;
}

export interface BrowserPackageMetadata {
  assemblies: BrowserAssemblyMetadata[];
  inspectionError: string | null;
}

export interface BrowserPackageOpportunities {
  package: string;
  version: string;
  activeFramework: string;
  categories: BrowserOpportunityCategory[];
  totalOpportunities: number;
  isComplete: boolean;
  inspectionError: string | null;
}

export interface BrowserPackageSurface {
  package: string;
  version: string;
  frameworks: string[];
  activeFramework: string;
  defaultAssemblyId: string;
  assemblies: BrowserAssemblySurface[];
  types: BrowserTypeSurface[];
  accessibility: BrowserAccessibilityDescriptor[];
  totalMembers: number;
  documents: BrowserPackageDocument[];
  inspectionErrors: string[];
  inspectionError: string | null;
}

export interface BrowserParameterSurface {
  name: string;
  type: string;
  modifier: string | null;
  hasDefault: boolean;
  defaultValue: string | null;
  description: string | null;
}

export interface BrowserSource {
  provider: string;
  provenance: string;
  url: string | null;
  pdbSourceLimitation: string | null;
  text: string;
}

export interface BrowserTypeCandidate {
  key: string;
  name: string;
  full: string;
}

export interface BrowserTypeComposition {
  methods: number;
  properties: number;
  fields: number;
  events: number;
  constructors: number;
  operators: number;
  explicitInterfaceImplementations: number;
  extensionMethods: number;
  static: number;
  unsafe: number;
  async: number;
  virtual: number;
  abstract: number;
  override: number;
  extension: number;
  obsolete: number;
  total: number;
}

export interface BrowserTypeGraphEdge {
  fromId: string;
  toId: string;
  kind: string;
}

export interface BrowserTypeGraphNode {
  id: string;
  displayName: string;
  role: string;
}

export interface BrowserTypeMetadata {
  fullName: string;
  namespace: string | null;
  name: string;
  kind: string;
  modifiers: string[];
  accessibility: string | null;
  assembly: string | null;
  baseType: string | null;
  interfaces: string[];
  derivedTypes: string[];
  typeParameters: BrowserTypeParameter[];
  attributes: string[];
  enumUnderlyingType: string | null;
  composition: BrowserTypeComposition | null;
  graphNodes: BrowserTypeGraphNode[];
  graphEdges: BrowserTypeGraphEdge[];
  inspectionFailures: string[];
}

export interface BrowserTypeParameter {
  name: string;
  variance: string | null;
  constraints: string[];
}

export interface BrowserTypeSearchHit {
  key: string;
  kind: string;
}

export interface BrowserTypeSurface {
  id: string;
  definitionId: string;
  queryId: string;
  metadataId: string;
  name: string;
  displayName: string;
  namespace: string;
  kind: string;
  accessibility: string;
  accessibilityId: string;
  assembly: string;
  assemblyId: string;
  assemblyName: string;
  members: number;
  signature: string;
  api: BrowserMemberSurface[];
  platformPack: string | null;
}

export interface BrowserVocabularyDocument {
  schema_version: number;
  sections: BrowserVocabularySection[];
}

export interface BrowserVocabularyField {
  id: string;
  label: string;
  summary: string;
  type: string;
  operators: string[];
}

export interface BrowserVocabularySection {
  id: string;
  name: string;
  summary: string;
  categories: string[];
  accepted_by: string[];
  fields: BrowserVocabularyField[];
  values: unknown[];
}

export interface BrowserWorkspacePackage {
  package: string;
  version: string;
  framework: string;
}

export declare function initializeEngine(onStatus?: (status: string) => void): Promise<unknown>;
export declare function buildIdentity(): BrowserBuildIdentity;
export declare function cancelSourceQuery(): void;
export declare function configureHost(origin: string): void;
export declare function expandPlatformCallGraph(targetFramework: string, assembly: string, pack: string, assemblyVersion: string, assemblyCulture: string | null, assemblyPublicKeyToken: string | null, typeFullName: string, memberName: string, selectorKey: string, metadataToken: number): Promise<BrowserCallGraph>;
export declare function getPackageDocument(packageId: string, version: string, path: string): Promise<BrowserPackageDocumentContent>;
export declare function listHomeDemos(): BrowserHomeDemoCatalog;
export declare function listVocabulary(): BrowserVocabularyDocument;
export declare function loadRuntimePack(targetFramework: string): Promise<string>;
export declare function loadRuntimePackAssembly(targetFramework: string, assemblyFileName: string, pack: string): Promise<string>;
export declare function matchPackageDependencyCoordinate(packageId: string, declaredRange: string | null, candidatesJson: string): BrowserDependencyCoordinateMatch;
export declare function packageCacheStats(): BrowserPackageCacheStats;
export declare function queryGraphMemberSurface(packageId: string, version: string, targetFramework: string, assemblyName: string, typeIdentity: string, memberName: string, selectorKey: string, metadataToken: number): Promise<BrowserMemberSurface>;
export declare function queryMemberAnnotatedSource(packageId: string, version: string, targetFramework: string, assemblyName: string, typeIdentity: string, typeQueryId: string, memberName: string, memberSignature: string, selectorKey: string, metadataToken: number, styleOptionsJson: string): Promise<BrowserAnnotatedSource>;
export declare function queryMemberCallGraph(packageId: string, version: string, targetFramework: string, assemblyName: string, typeIdentity: string, typeQueryId: string, memberName: string, memberSignature: string, selectorKey: string, metadataToken: number, workspaceJson: string): Promise<BrowserCallGraph>;
export declare function queryMemberDocumentation(packageId: string, version: string, framework: string, assemblyName: string, documentationId: string): Promise<BrowserMemberDocumentation>;
export declare function queryMemberFacts(packageId: string, version: string, targetFramework: string, assemblyName: string, typeId: string, memberName: string, memberSignature: string): Promise<string>;
export declare function queryMemberSource(packageId: string, version: string, targetFramework: string, assemblyName: string, typeIdentity: string, memberName: string, selectorKey: string, metadataToken: number, styleOptionsJson: string): Promise<BrowserSource>;
export declare function queryPackage(packageId: string, version: string, targetFramework: string): Promise<BrowserPackageSurface>;
export declare function queryPackageDependencies(packageId: string, version: string, targetFramework: string, assemblyId: string): Promise<BrowserPackageDependencies>;
export declare function queryPackageHeapEntries(packageId: string, version: string, targetFramework: string, assemblyFileName: string, heap: string): Promise<BrowserHeapListing>;
export declare function queryPackageIntegrations(packageId: string, version: string, targetFramework: string): Promise<BrowserPackageIntegrations>;
export declare function queryPackageMetadata(packageId: string, version: string, targetFramework: string): Promise<BrowserPackageMetadata>;
export declare function queryPackageMetadataTable(packageId: string, version: string, targetFramework: string, assemblyFileName: string, tableIndex: number, startRowId: number, maxRows: number): Promise<BrowserMetadataWindow>;
export declare function queryPackageOpportunities(packageId: string, version: string, targetFramework: string): Promise<BrowserPackageOpportunities>;
export declare function queryPackagePerformance(packageId: string, version: string, targetFramework: string): Promise<string>;
export declare function queryPackageVersions(packageId: string): Promise<string[]>;
export declare function queryPlatformHeapEntries(targetFramework: string, assemblyFileName: string, pack: string, heap: string): Promise<BrowserHeapListing>;
export declare function queryPlatformIntegrations(targetFramework: string, assemblyFileName: string, pack: string): Promise<BrowserPackageIntegrations>;
export declare function queryPlatformMetadata(targetFramework: string, assemblyFileName: string, pack: string): Promise<BrowserPackageMetadata>;
export declare function queryPlatformMetadataTable(targetFramework: string, assemblyFileName: string, pack: string, tableIndex: number, startRowId: number, maxRows: number): Promise<BrowserMetadataWindow>;
export declare function queryPlatformOpportunities(targetFramework: string, assemblyFileName: string, pack: string): Promise<BrowserPackageOpportunities>;
export declare function queryPlatformPerformance(targetFramework: string, assemblyFileName: string, pack: string): Promise<string>;
export declare function queryTypeMemberSource(packageId: string, version: string, targetFramework: string, assemblyName: string, typeIdentity: string, memberName: string, selectorKey: string, metadataToken: number, styleOptionsJson: string): Promise<BrowserSource>;
export declare function queryTypeProjection(packageId: string, version: string, targetFramework: string, assemblyName: string, typeId: string): Promise<BrowserTypeMetadata>;
export declare function queryTypeSource(packageId: string, version: string, targetFramework: string, assemblyName: string, typeIdentity: string, styleOptionsJson: string): Promise<BrowserSource>;
export declare function resolveHomeDemo(scenarioId: string): BrowserHomeDemoResolveResult;
export declare function resolvePackageDependencyVersion(packageId: string, declaredRange: string | null): Promise<string>;
export declare function runHomeDemo(scenarioId: string): Promise<BrowserHomeDemoRunResult>;
export declare function searchTypes(query: string, candidatesJson: string): BrowserTypeSearchHit[];
